// packages/solid/src/components/DiffSplitWidgetLineNormal.tsx
import { SplitSide, type DiffFile } from "@git-diff-view/core";
import { emptyBGName } from "@git-diff-view/utils";
import { createMemo, Show } from "solid-js";

import { useDomWidth, useRenderWidget, useSyncHeight } from "../hooks";

import { useDiffWidgetContext } from "./DiffWidgetContext";

export const DiffSplitWidgetLine = (props: {
  index: number;
  side: SplitSide;
  diffFile: DiffFile;
  lineNumber: number;
}) => {
  const renderWidget = useRenderWidget();

  const [widget, setWidget] = useDiffWidgetContext() || [];

  const oldLine = createMemo(() => props.diffFile.getSplitLeftLine(props.index));

  const newLine = createMemo(() => props.diffFile.getSplitRightLine(props.index));

  const oldLineWidget = createMemo(
    () =>
      !!oldLine()?.lineNumber && widget?.()?.side === SplitSide.old && widget?.()?.lineNumber === oldLine()?.lineNumber
  );

  const newLineWidget = createMemo(
    () =>
      !!newLine()?.lineNumber && widget?.()?.side === SplitSide.new && widget?.()?.lineNumber === newLine()?.lineNumber
  );

  const currentLine = createMemo(() => (props.side === SplitSide.old ? oldLine() : newLine()));

  const currentIsHidden = createMemo(() => currentLine()?.isHidden);

  const lineSelector = createMemo(() => `div[data-line="${props.lineNumber}-widget-content"]`);

  const lineWrapperSelector = createMemo(() => `tr[data-line="${props.lineNumber}-widget"]`);

  const wrapperSelector = createMemo(() =>
    props.side === SplitSide.old ? ".old-diff-table-wrapper" : ".new-diff-table-wrapper"
  );

  const currentWidget = createMemo(() => (props.side === SplitSide.old ? oldLineWidget() : newLineWidget()));

  const observeSide = createMemo(
    () => SplitSide[currentWidget() ? props.side : props.side === SplitSide.old ? SplitSide.new : SplitSide.old]
  );

  const currentIsShow = createMemo(
    () => (!!oldLineWidget() || !!newLineWidget()) && !currentIsHidden() && !newLine()?.isHidden && !!renderWidget
  );

  const currentEnable = createMemo(() => currentWidget() && !!currentIsShow());

  const onCloseWidget = () => setWidget?.({});

  useSyncHeight({
    selector: lineSelector,
    wrapper: lineWrapperSelector,
    side: observeSide,
    enable: currentIsShow,
  });

  const width = useDomWidth({
    selector: wrapperSelector,
    enable: currentEnable,
  });

  return (
    <Show when={currentIsShow()}>
      <tr
        data-line={`${props.lineNumber}-widget`}
        data-state="widget"
        data-side={SplitSide[props.side]}
        class="diff-line diff-line-widget"
      >
        {currentWidget() ? (
          <td class={`diff-line-widget-${SplitSide[props.side]}-content p-0`} colspan={2}>
            <div
              data-line={`${props.lineNumber}-widget-content`}
              data-side={SplitSide[props.side]}
              class="diff-line-widget-wrapper sticky left-0 z-[1]"
              style={{ width: width() + "px" }}
            >
              {width() > 0 &&
                renderWidget()?.({
                  diffFile: props.diffFile,
                  side: props.side,
                  lineNumber: currentLine()?.lineNumber || 0,
                  onClose: onCloseWidget,
                })}
            </div>
          </td>
        ) : (
          <td
            class={`diff-line-widget-${SplitSide[props.side]}-placeholder select-none p-0`}
            style={{ "background-color": `var(${emptyBGName})` }}
            colspan={2}
          >
            <div data-line={`${props.lineNumber}-widget-content`} data-side={SplitSide[props.side]} />
          </td>
        )}
      </tr>
    </Show>
  );
};

// packages/svelte/src/lib/components/DiffSplitWidgetLineNormal.svelte
<script lang="ts">
	import { getRenderWidget } from '$lib/context/renderWidget.js';
	import { getWidget } from '$lib/context/widget.js';
	import { useDomWidth } from '$lib/hooks/useDomWidth.svelte.js';
	import { useSyncHeight } from '$lib/hooks/useSyncHeight.svelte.js';
	import { SplitSide, type DiffFile } from '@git-diff-view/core';
	import { emptyBGName } from '@git-diff-view/utils';

	interface Props {
		index: number;
		side: SplitSide;
		diffFile: DiffFile;
		lineNumber: number;
	}

	let props: Props = $props();

	const renderWidget = $derived.by(getRenderWidget());

	const widget = $derived.by(getWidget());

	const oldLine = $derived.by(() => props.diffFile.getSplitLeftLine(props.index));

	const newLine = $derived.by(() => props.diffFile.getSplitRightLine(props.index));

	const oldLineWidget = $derived.by(
		() =>
			!!oldLine?.lineNumber &&
			widget?.side === SplitSide.old &&
			widget?.lineNumber === oldLine?.lineNumber
	);

	const newLineWidget = $derived.by(
		() =>
			!!newLine?.lineNumber &&
			widget?.side === SplitSide.new &&
			widget?.lineNumber === newLine?.lineNumber
	);

	const currentLine = $derived.by(() => (props.side === SplitSide.old ? oldLine : newLine));

	const currentIsHidden = $derived.by(() => currentLine?.isHidden);

	const lineSelector = $derived.by(() => `div[data-line="${props.lineNumber}-widget-content"]`);

	const lineWrapperSelector = $derived.by(() => `tr[data-line="${props.lineNumber}-widget"]`);

	const wrapperSelector = $derived.by(() =>
		props.side === SplitSide.old ? '.old-diff-table-wrapper' : '.new-diff-table-wrapper'
	);

	const currentWidget = $derived.by(() =>
		props.side === SplitSide.old ? oldLineWidget : newLineWidget
	);

	const observeSide = $derived.by(
		() =>
			SplitSide[
				currentWidget ? props.side : props.side === SplitSide.old ? SplitSide.new : SplitSide.old
			]
	);

	const currentIsShow = $derived.by(
		() =>
			(!!oldLineWidget || !!newLineWidget) &&
			!currentIsHidden &&
			!newLine?.isHidden &&
			!!renderWidget
	);

	const currentEnable = $derived.by(() => currentWidget && !!currentIsShow);

	const onCloseWidget = () => {
		widget.side = undefined;
		widget.lineNumber = undefined;
	};

	useSyncHeight({
		selector: () => lineSelector,
		wrapper: () => lineWrapperSelector,
		side: () => observeSide,
		enable: () => currentIsShow
	});

	const width = $derived.by(
		useDomWidth({
			selector: () => wrapperSelector,
			enable: () => currentEnable
		})
	);
</script>

{#if currentIsShow}
	<tr
		data-line={`${props.lineNumber}-widget`}
		data-state="widget"
		data-side={SplitSide[props.side]}
		class="diff-line diff-line-widget"
	>
		{#if currentWidget}
			<td class={`diff-line-widget-${SplitSide[props.side]}-content p-0`} colspan={2}>
				<div
					data-line={`${props.lineNumber}-widget-content`}
					data-side={SplitSide[props.side]}
					class="diff-line-widget-wrapper sticky left-0 z-[1]"
					style={` width: ${width}px `}
				>
					{#if width > 0}
						{@render renderWidget({
							diffFile: props.diffFile,
							side: props.side,
							lineNumber: currentLine?.lineNumber || 0,
							onClose: onCloseWidget
						})}
					{/if}
				</div>
			</td>
		{:else}
			<td
				class={`diff-line-widget-${SplitSide[props.side]}-placeholder select-none p-0`}
				style={`background-color: var(${emptyBGName})`}
				colspan={2}
			>
				<div
					data-line={`${props.lineNumber}-widget-content`}
					data-side={SplitSide[props.side]}
				></div>
			</td>
		{/if}
	</tr>
{/if}
