// packages/vue/src/components/DiffSplitHunkLineNormal.tsx
import { composeLen, type DiffFile } from "@git-diff-view/core";
import { computed, defineComponent, ref } from "vue";

import { useSubscribeDiffFile } from "../hooks/useSubscribeDiffFile";
import { useSyncHeight } from "../hooks/useSyncHeight";

import { hunkContentBGName, hunkContentColorName, hunkLineNumberBGName, plainLineNumberColorName } from "./color";
import { ExpandAll, ExpandDown, ExpandUp } from "./DiffExpand";
import { SplitSide } from "./DiffView";

export const DiffSplitHunkLine = defineComponent(
  (props: { index: number; side: SplitSide; diffFile: DiffFile; lineNumber: number }) => {
    const currentHunk = ref(props.diffFile.getSplitHunkLine(props.index));

    const enableExpand = ref(props.diffFile.getExpandEnabled());

    const lineSelector = computed(() => `tr[data-line="${props.lineNumber}-hunk"]`);

    const currentShowExpand = computed(() => props.side === SplitSide.old);

    const currentSyncHeightSide = computed(() => SplitSide[SplitSide.old]);

    const currentShowExpandAll = ref(
      currentHunk.value &&
        currentHunk.value.splitInfo &&
        currentHunk.value.splitInfo.endHiddenIndex - currentHunk.value.splitInfo.startHiddenIndex < composeLen
    );

    const currentIsShow = ref(
      currentHunk.value &&
        currentHunk.value.splitInfo &&
        currentHunk.value.splitInfo.startHiddenIndex < currentHunk.value.splitInfo.endHiddenIndex
    );

    useSubscribeDiffFile(props, (diffFile) => {
      currentHunk.value = diffFile.getSplitHunkLine(props.index);

      enableExpand.value = diffFile.getExpandEnabled();

      currentShowExpandAll.value =
        currentHunk.value &&
        currentHunk.value.splitInfo &&
        currentHunk.value.splitInfo.endHiddenIndex - currentHunk.value.splitInfo.startHiddenIndex < composeLen;

      currentIsShow.value =
        currentHunk.value &&
        currentHunk.value.splitInfo &&
        currentHunk.value.splitInfo.startHiddenIndex < currentHunk.value.splitInfo.endHiddenIndex;
    });

    const currentEnableSyncHeight = computed(() => props.side === SplitSide.new && currentIsShow.value);

    useSyncHeight({
      selector: lineSelector,
      side: currentSyncHeightSide,
      enable: currentEnableSyncHeight,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr
          data-line={`${props.lineNumber}-hunk`}
          data-state="hunk"
          data-side={SplitSide[props.side]}
          style={{ backgroundColor: `var(${hunkContentBGName})` }}
          class="diff-line diff-line-hunk"
        >
          {currentShowExpand.value ? (
            <>
              <td
                class="diff-line-hunk-action sticky left-0 p-[1px] w-[1%] min-w-[40px] select-none"
                style={{
                  backgroundColor: `var(${hunkLineNumberBGName})`,
                  color: `var(${plainLineNumberColorName})`,
                }}
              >
                {enableExpand.value ? (
                  currentShowExpandAll.value ? (
                    <button
                      class="w-full hover:bg-blue-300 flex justify-center items-center py-[6px] cursor-pointer rounded-[2px]"
                      title="Expand All"
                      onClick={() => props.diffFile.onSplitHunkExpand("all", props.index)}
                    >
                      <ExpandAll className="fill-current" />
                    </button>
                  ) : (
                    <>
                      <button
                        class="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
                        title="Expand Down"
                        onClick={() => props.diffFile.onSplitHunkExpand("down", props.index)}
                      >
                        <ExpandDown className="fill-current" />
                      </button>
                      <button
                        class="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
                        title="Expand Up"
                        onClick={() => props.diffFile.onSplitHunkExpand("up", props.index)}
                      >
                        <ExpandUp className="fill-current" />
                      </button>
                    </>
                  )
                ) : (
                  <span>&ensp;</span>
                )}
              </td>
              <td
                class="diff-line-hunk-content pr-[10px] align-middle"
                style={{ backgroundColor: `var(${hunkContentBGName})` }}
              >
                <div
                  class="pl-[1.5em]"
                  style={{
                    color: `var(${hunkContentColorName})`,
                  }}
                >
                  {currentHunk.value.splitInfo.plainText}
                </div>
              </td>
            </>
          ) : (
            <td class="diff-line-hunk-placeholder" colspan={2} style={{ backgroundColor: `var(${hunkContentBGName})` }}>
              <span>&ensp;</span>
            </td>
          )}
        </tr>
      );
    };
  },
  { name: "DiffSplitHunkLine", props: ["diffFile", "index", "lineNumber", "side"] }
);

export const DiffSplitLastHunkLine = defineComponent(
  (props: { side: SplitSide; diffFile: DiffFile }) => {
    const enableHunkAction = computed(() => props.side === SplitSide.old);

    const lineSelector = computed(() => `tr[data-line="last-hunk"]`);

    const currentSyncHeightSide = computed(() => SplitSide[SplitSide.old]);


    const currentIsShow = ref(props.diffFile.getNeedShowExpandAll("split") && props.diffFile.getExpandEnabled());

    useSubscribeDiffFile(
      props,
      (diffFile) => (currentIsShow.value = diffFile.getNeedShowExpandAll("split") && diffFile.getExpandEnabled())
    );

    const currentEnableSyncHeight = computed(() => props.side === SplitSide.new && currentIsShow.value);

    useSyncHeight({
      selector: lineSelector,
      side: currentSyncHeightSide,
      enable: currentEnableSyncHeight,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr
          data-line="last-hunk"
          data-state="hunk"
          data-side={SplitSide[props.side]}
          class="diff-line diff-line-hunk"
        >
          {enableHunkAction.value ? (
            <>
              <td
                class="diff-line-hunk-action sticky left-0 p-[1px] w-[1%] min-w-[40px] select-none"
                style={{
                  backgroundColor: `var(${hunkLineNumberBGName})`,
                  color: `var(${plainLineNumberColorName})`,
                }}
              >
                <button
                  class="w-full hover:bg-blue-300 flex justify-center items-center py-[6px] cursor-pointer rounded-[2px]"
                  title="Expand Down"
                  onClick={() => props.diffFile.onSplitLastExpand()}
                >
                  <ExpandDown className="fill-current" />
                </button>
              </td>
              <td
                class="diff-line-hunk-content pr-[10px] align-middle"
                style={{ backgroundColor: `var(${hunkContentBGName})` }}
              >
                <span>&ensp;</span>
              </td>
            </>
          ) : (
            <td class="diff-line-hunk-placeholder" colspan={2} style={{ backgroundColor: `var(${hunkContentBGName})` }}>
              <span>&ensp;</span>
            </td>
          )}
        </tr>
      );
    };
  },
  { name: "DiffSplitLastHunkLine", props: ["diffFile", "side"] }
);

// packages/react/src/virtual/DiffSplitHunkLineNormal.tsx
import { composeLen, type DiffFile } from "@git-diff-view/core";
import * as React from "react";

import { SplitSide } from "..";
import { useSyncHeight } from "../hooks/useSyncHeight";

import { hunkContentBGName, hunkContentColorName, hunkLineNumberBGName, plainLineNumberColorName } from "./color";
import { ExpandAll, ExpandDown, ExpandUp } from "./DiffExpand";

const _DiffSplitHunkLine = ({
  index,
  diffFile,
  side,
  lineNumber,
}: {
  index: number;
  side: SplitSide;
  diffFile: DiffFile;
  lineNumber: number;
}) => {
  const currentHunk = diffFile.getSplitHunkLine(index);

  const expandEnabled = diffFile.getExpandEnabled();

  useSyncHeight({
    selector: `tr[data-line="${lineNumber}-hunk"]`,
    side: SplitSide[SplitSide.old],
    enable: side === SplitSide.new,
  });

  const enableHunkAction = side === SplitSide.old;

  const isExpandAll =
    currentHunk &&
    currentHunk.splitInfo &&
    currentHunk.splitInfo.endHiddenIndex - currentHunk.splitInfo.startHiddenIndex < composeLen;

  return (
    <tr
      data-line={`${lineNumber}-hunk`}
      data-state="hunk"
      data-side={SplitSide[side]}
      className="diff-line diff-line-hunk select-none"
    >
      {enableHunkAction ? (
        <>
          <td
            className="diff-line-hunk-action sticky left-0 p-[1px] w-[1%] min-w-[40px]"
            style={{
              backgroundColor: `var(${hunkLineNumberBGName})`,
              color: `var(${plainLineNumberColorName})`,
            }}
          >
            {expandEnabled ? (
              isExpandAll ? (
                <button
                  className="w-full hover:bg-blue-300 flex justify-center items-center py-[6px] cursor-pointer rounded-[2px]"
                  title="Expand All"
                  onClick={() => diffFile.onSplitHunkExpand("all", index)}
                >
                  <ExpandAll className="fill-current" />
                </button>
              ) : (
                <>
                  <button
                    className="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
                    title="Expand Down"
                    onClick={() => diffFile.onSplitHunkExpand("down", index)}
                  >
                    <ExpandDown className="fill-current" />
                  </button>
                  <button
                    className="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
                    title="Expand Up"
                    onClick={() => diffFile.onSplitHunkExpand("up", index)}
                  >
                    <ExpandUp className="fill-current" />
                  </button>
                </>
              )
            ) : (
              <span>&ensp;</span>
            )}
          </td>
          <td
            className="diff-line-hunk-content pr-[10px] align-middle"
            style={{ backgroundColor: `var(${hunkContentBGName})` }}
          >
            <div
              className="pl-[1.5em]"
              style={{
                color: `var(${hunkContentColorName})`,
              }}
            >
              {currentHunk.splitInfo.plainText}
            </div>
          </td>
        </>
      ) : (
        <td className="diff-line-hunk-placeholder" colSpan={2} style={{ backgroundColor: `var(${hunkContentBGName})` }}>
          <span>&ensp;</span>
        </td>
      )}
    </tr>
  );
};

export const DiffSplitHunkLine = ({
  index,
  diffFile,
  side,
  lineNumber,
}: {
  index: number;
  side: SplitSide;
  diffFile: DiffFile;
  lineNumber: number;
}) => {
  const currentHunk = diffFile.getSplitHunkLine(index);

  const currentIsShow =
    currentHunk &&
    currentHunk.splitInfo &&
    currentHunk.splitInfo.startHiddenIndex < currentHunk.splitInfo.endHiddenIndex;

  if (!currentIsShow) return null;

  return <_DiffSplitHunkLine index={index} diffFile={diffFile} side={side} lineNumber={lineNumber} />;
};

export const DiffSplitLastHunkLine = ({ diffFile, side }: { side: SplitSide; diffFile: DiffFile }) => {
  const currentIsShow = diffFile.getNeedShowExpandAll("split");

  const expandEnabled = diffFile.getExpandEnabled();

  const countRef = React.useRef(0);

  const enableHunkAction = side === SplitSide.old;

  if (!currentIsShow || !expandEnabled) return null;

  return (
    <tr
      data-line="last-hunk"
      data-state="hunk"
      data-side={SplitSide[side]}
      className="diff-line diff-line-hunk select-none"
    >
      {enableHunkAction ? (
        <>
          <td
            className="diff-line-hunk-action sticky left-0 p-[1px] w-[1%] min-w-[40px]"
            style={{
              backgroundColor: `var(${hunkLineNumberBGName})`,
              color: `var(${plainLineNumberColorName})`,
            }}
          >
            <button
              className="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
              title="Expand Down"
              onClick={() => {
                countRef.current++;
                diffFile.onSplitLastExpand(countRef.current >= 3);
              }}
            >
              <ExpandDown className="fill-current" />
            </button>
          </td>
          <td
            className="diff-line-hunk-content pr-[10px] align-middle"
            style={{ backgroundColor: `var(${hunkContentBGName})` }}
          >
            <span>&ensp;</span>
          </td>
        </>
      ) : (
        <td className="diff-line-hunk-placeholder" colSpan={2} style={{ backgroundColor: `var(${hunkContentBGName})` }}>
          <span>&ensp;</span>
        </td>
      )}
    </tr>
  );
};
