// packages/vue/src/components/DiffUnifiedHunkLine.tsx
import { composeLen } from "@git-diff-view/core";
import { defineComponent, ref } from "vue";

import { useEnableWrap } from "../context";
import { useSubscribeDiffFile } from "../hooks/useSubscribeDiffFile";

import { hunkContentBGName, hunkContentColorName, hunkLineNumberBGName, plainLineNumberColorName } from "./color";
import { ExpandAll, ExpandDown, ExpandUp } from "./DiffExpand";

import type { DiffFile } from "@git-diff-view/core";

export const DiffUnifiedHunkLine = defineComponent(
  (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
    const currentHunk = ref(props.diffFile.getUnifiedHunkLine(props.index));

    const enableExpand = ref(props.diffFile.getExpandEnabled());

    const enableWrap = useEnableWrap();

    const currentIsShow = ref(
      currentHunk.value &&
        currentHunk.value.unifiedInfo &&
        currentHunk.value.unifiedInfo.startHiddenIndex < currentHunk.value.unifiedInfo.endHiddenIndex
    );

    const currentIsEnableAll = ref(
      currentHunk.value &&
        currentHunk.value.unifiedInfo &&
        currentHunk.value.unifiedInfo.endHiddenIndex - currentHunk.value.unifiedInfo.startHiddenIndex < composeLen
    );

    useSubscribeDiffFile(props, (diffFile) => {
      currentHunk.value = diffFile.getUnifiedHunkLine(props.index);

      enableExpand.value = diffFile.getExpandEnabled();

      currentIsShow.value =
        currentHunk.value &&
        currentHunk.value.unifiedInfo &&
        currentHunk.value.unifiedInfo.startHiddenIndex < currentHunk.value.unifiedInfo.endHiddenIndex;

      currentIsEnableAll.value =
        currentHunk.value &&
        currentHunk.value.unifiedInfo &&
        currentHunk.value.unifiedInfo.endHiddenIndex - currentHunk.value.unifiedInfo.startHiddenIndex < composeLen;
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr data-line={`${props.lineNumber}-hunk`} data-state="hunk" class="diff-line diff-line-hunk">
          <td
            class="diff-line-hunk-action sticky left-0 w-[1%] min-w-[100px] select-none"
            style={{
              backgroundColor: `var(${hunkLineNumberBGName})`,
              color: `var(${plainLineNumberColorName})`,
            }}
          >
            {enableExpand.value ? (
              currentIsEnableAll.value ? (
                <button
                  class="w-full hover:bg-blue-300 flex justify-center items-center py-[6px] cursor-pointer rounded-[2px]"
                  title="Expand All"
                  onClick={() => props.diffFile.onUnifiedHunkExpand("all", props.index)}
                >
                  <ExpandAll className="fill-current" />
                </button>
              ) : (
                <>
                  <button
                    class="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
                    title="Expand Down"
                    onClick={() => props.diffFile.onUnifiedHunkExpand("down", props.index)}
                  >
                    <ExpandDown className="fill-current" />
                  </button>
                  <button
                    class="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
                    title="Expand Up"
                    onClick={() => props.diffFile.onUnifiedHunkExpand("up", props.index)}
                  >
                    <ExpandUp className="fill-current" />
                  </button>
                </>
              )
            ) : null}
          </td>
          <td
            class="diff-line-hunk-content pr-[10px] align-middle"
            style={{ backgroundColor: `var(${hunkContentBGName})` }}
          >
            <div
              class="pl-[1.5em]"
              style={{
                whiteSpace: enableWrap.value ? "pre-wrap" : "pre",
                wordBreak: enableWrap.value ? "break-all" : "initial",
                color: `var(${hunkContentColorName})`,
              }}
            >
              {currentHunk.value.unifiedInfo.plainText}
            </div>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffUnifiedHunkLine", props: ["index", "diffFile", "lineNumber"] }
);

export const DiffUnifiedLastHunkLine = defineComponent(
  (props: { diffFile: DiffFile }) => {
    const currentIsShow = ref(props.diffFile.getNeedShowExpandAll("unified") && props.diffFile.getExpandEnabled());

    const enableWrap = useEnableWrap();

    useSubscribeDiffFile(
      props,
      (diffFile) => (currentIsShow.value = diffFile.getNeedShowExpandAll("unified") && diffFile.getExpandEnabled())
    );

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr data-line="last-hunk" data-state="hunk" class="diff-line diff-line-hunk">
          <td
            class="diff-line-hunk-action sticky left-0 w-[1%] min-w-[100px] select-none"
            style={{
              position: enableWrap.value ? "relative" : "sticky",
              backgroundColor: `var(${hunkLineNumberBGName})`,
              color: `var(${plainLineNumberColorName})`,
            }}
          >
            <button
              class="w-full hover:bg-blue-300 flex justify-center items-center py-[6px] cursor-pointer rounded-[2px]"
              title="Expand Down"
              onClick={() => props.diffFile.onUnifiedLastExpand()}
            >
              <ExpandDown className="fill-current" />
            </button>
          </td>
          <td
            class="diff-line-hunk-content pr-[10px] align-middle"
            style={{ backgroundColor: `var(${hunkContentBGName})` }}
          >
            <span>&ensp;</span>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffUnifiedLastHunkLine", props: ["diffFile"] }
);

// packages/react/src/virtual/DiffUnifiedHunkLine.tsx
import { composeLen } from "@git-diff-view/core";
import * as React from "react";
import { useCallback } from "react";

import { useDiffViewContext } from "..";

import { hunkContentBGName, hunkContentColorName, hunkLineNumberBGName, plainLineNumberColorName } from "./color";
import { ExpandAll, ExpandDown, ExpandUp } from "./DiffExpand";

import type { DiffFile } from "@git-diff-view/core";

const _DiffUnifiedHunkLine = ({
  index,
  diffFile,
  lineNumber,
}: {
  index: number;
  diffFile: DiffFile;
  lineNumber: number;
}) => {
  const currentHunk = diffFile.getUnifiedHunkLine(index);

  const expandEnabled = diffFile.getExpandEnabled();

  const { useDiffContext } = useDiffViewContext();

  const enableWrap = useDiffContext(useCallback((s) => s.enableWrap, []));

  const isExpandAll =
    currentHunk &&
    currentHunk.unifiedInfo &&
    currentHunk.unifiedInfo.endHiddenIndex - currentHunk.unifiedInfo.startHiddenIndex < composeLen;

  return (
    <tr data-line={`${lineNumber}-hunk`} data-state="hunk" className="diff-line diff-line-hunk select-none">
      <td
        className="diff-line-hunk-action sticky left-0 p-[1px] w-[1%] min-w-[100px]"
        style={{
          backgroundColor: `var(${hunkLineNumberBGName})`,
          color: `var(${plainLineNumberColorName})`,
        }}
      >
        {expandEnabled ? (
          isExpandAll ? (
            <button
              className="w-full hover:bg-blue-300 flex justify-center items-center py-[6px] cursor-pointer rounded-[2px]"
              title="Expand All"
              onClick={() => diffFile.onUnifiedHunkExpand("all", index)}
            >
              <ExpandAll className="fill-current" />
            </button>
          ) : (
            <>
              <button
                className="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
                title="Expand Down"
                onClick={() => diffFile.onUnifiedHunkExpand("down", index)}
              >
                <ExpandDown className="fill-current" />
              </button>
              <button
                className="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
                title="Expand Up"
                onClick={() => diffFile.onUnifiedHunkExpand("up", index)}
              >
                <ExpandUp className="fill-current" />
              </button>
            </>
          )
        ) : null}
      </td>
      <td
        className="diff-line-hunk-content pr-[10px] align-middle"
        style={{ backgroundColor: `var(${hunkContentBGName})` }}
      >
        <div
          className="pl-[1.5em]"
          style={{
            whiteSpace: enableWrap ? "pre-wrap" : "pre",
            wordBreak: enableWrap ? "break-all" : "initial",
            color: `var(${hunkContentColorName})`,
          }}
        >
          {currentHunk.unifiedInfo.plainText}
        </div>
      </td>
    </tr>
  );
};

export const DiffUnifiedHunkLine = ({
  index,
  diffFile,
  lineNumber,
}: {
  index: number;
  diffFile: DiffFile;
  lineNumber: number;
}) => {
  const currentHunk = diffFile.getUnifiedHunkLine(index);

  const currentIsShow =
    currentHunk &&
    currentHunk.unifiedInfo &&
    currentHunk.unifiedInfo.startHiddenIndex < currentHunk.unifiedInfo.endHiddenIndex;

  if (!currentIsShow) return null;

  return <_DiffUnifiedHunkLine index={index} diffFile={diffFile} lineNumber={lineNumber} />;
};

export const DiffUnifiedLastHunkLine = ({ diffFile }: { diffFile: DiffFile }) => {
  const currentIsShow = diffFile.getNeedShowExpandAll("unified");

  const expandEnabled = diffFile.getExpandEnabled();

  if (!currentIsShow || !expandEnabled) return null;

  return (
    <tr data-line="last-hunk" data-state="hunk" className="diff-line diff-line-hunk select-none">
      <td
        className="diff-line-hunk-action sticky left-0 w-[1%] min-w-[100px]"
        style={{
          backgroundColor: `var(${hunkLineNumberBGName})`,
          color: `var(${plainLineNumberColorName})`,
        }}
      >
        <button
          className="w-full hover:bg-blue-300 flex justify-center items-center py-[2px] cursor-pointer rounded-[2px]"
          title="Expand Down"
          onClick={() => diffFile.onUnifiedLastExpand()}
        >
          <ExpandDown className="fill-current" />
        </button>
      </td>
      <td
        className="diff-line-hunk-content pr-[10px] align-middle"
        style={{ backgroundColor: `var(${hunkContentBGName})` }}
      >
        <span>&ensp;</span>
      </td>
    </tr>
  );
};
