// packages/vue/src/components/DiffSplitWidgetLineWrap.tsx
import { borderColorName, emptyBGName } from "@git-diff-view/utils";
import { computed, defineComponent, ref } from "vue";

import { useSetWidget, useSlots, useWidget } from "../context";
import { useSubscribeDiffFile } from "../hooks/useSubscribeDiffFile";

import { SplitSide } from "./DiffView";

import type { DiffFile } from "@git-diff-view/core";

export const DiffSplitWidgetLine = defineComponent(
  (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
    const slots = useSlots();

    const widget = useWidget();

    const setWidget = useSetWidget();

    const oldLine = ref(props.diffFile.getSplitLeftLine(props.index));

    const newLine = ref(props.diffFile.getSplitRightLine(props.index));

    const oldLineWidget = computed(
      () =>
        oldLine.value.lineNumber &&
        widget.value.side === SplitSide.old &&
        widget.value.lineNumber === oldLine.value.lineNumber
    );

    const newLineWidget = computed(
      () =>
        newLine.value.lineNumber &&
        widget.value.side === SplitSide.new &&
        widget.value.lineNumber === newLine.value.lineNumber
    );

    useSubscribeDiffFile(props, (diffFile) => {
      oldLine.value = diffFile.getSplitLeftLine(props.index);

      newLine.value = diffFile.getSplitRightLine(props.index);
    });

    const currentIsShow = computed(
      () =>
        (!!oldLineWidget.value || !!newLineWidget.value) &&
        !oldLine.value.isHidden &&
        !newLine.value.isHidden &&
        !!slots.widget
    );

    const onCloseWidget = () => setWidget({});

    return () => {
      if (!currentIsShow.value) return null;

      const oldWidgetRendered = oldLineWidget.value
        ? slots.widget?.({
            diffFile: props.diffFile,
            side: SplitSide.old,
            lineNumber: oldLine.value.lineNumber,
            onClose: onCloseWidget,
          })
        : null;

      const newWidgetRendered = newLineWidget.value
        ? slots.widget?.({
            diffFile: props.diffFile,
            side: SplitSide.new,
            lineNumber: newLine.value.lineNumber,
            onClose: onCloseWidget,
          })
        : null;

      return (
        <tr data-line={`${props.lineNumber}-widget`} data-state="widget" class="diff-line diff-line-widget">
          {oldWidgetRendered ? (
            <td class="diff-line-widget-old-content p-0" colspan={2}>
              <div class="diff-line-widget-wrapper">{oldWidgetRendered}</div>
            </td>
          ) : (
            <td
              class="diff-line-widget-old-placeholder select-none p-0"
              style={{ backgroundColor: `var(${emptyBGName})` }}
              colspan={2}
            >
              {newWidgetRendered && <span>&ensp;</span>}
            </td>
          )}
          {newWidgetRendered ? (
            <td
              class="diff-line-widget-new-content border-l-[1px] p-0"
              colspan={2}
              style={{ borderLeftColor: `var(${borderColorName})` }}
            >
              <div class="diff-line-widget-wrapper">{newWidgetRendered}</div>
            </td>
          ) : (
            <td
              class="diff-line-widget-new-placeholder select-none border-l-[1px] p-0"
              style={{ backgroundColor: `var(${emptyBGName})`, borderLeftColor: `var(${borderColorName})` }}
              colspan={2}
            >
              {oldWidgetRendered && <span>&ensp;</span>}
            </td>
          )}
        </tr>
      );
    };
  },
  { name: "DiffSplitWidgetLine", props: ["diffFile", "index", "lineNumber"] }
);

// packages/react/src/components/DiffSplitWidgetLineWrap.tsx
import * as React from "react";

import { useDiffViewContext, SplitSide } from "..";

import { borderColorName, emptyBGName } from "./color";
import { useDiffWidgetContext } from "./DiffWidgetContext";

import type { DiffFile } from "@git-diff-view/core";

const _DiffSplitWidgetLine = ({
  index,
  diffFile,
  lineNumber,
  oldLineWidget,
  newLineWidget,
}: {
  index: number;
  diffFile: DiffFile;
  lineNumber: number;
  oldLineWidget: boolean;
  newLineWidget: boolean;
}) => {
  const { useWidget } = useDiffWidgetContext();

  const setWidget = useWidget.getReadonlyState().setWidget;

  const { useDiffContext } = useDiffViewContext();

  const renderWidgetLine = useDiffContext.useShallowStableSelector((s) => s.renderWidgetLine);

  const oldLine = diffFile.getSplitLeftLine(index);

  const newLine = diffFile.getSplitRightLine(index);

  const oldWidgetRendered =
    oldLineWidget &&
    renderWidgetLine?.({ diffFile, side: SplitSide.old, lineNumber: oldLine.lineNumber, onClose: () => setWidget({}) });

  const newWidgetRendered =
    newLineWidget &&
    renderWidgetLine?.({ diffFile, side: SplitSide.new, lineNumber: newLine.lineNumber, onClose: () => setWidget({}) });

  if (!renderWidgetLine) return null;

  return (
    <tr data-line={`${lineNumber}-widget`} data-state="widget" className="diff-line diff-line-widget">
      {oldWidgetRendered ? (
        <td className="diff-line-widget-old-content p-0" colSpan={2}>
          <div className="diff-line-widget-wrapper">{oldWidgetRendered}</div>
        </td>
      ) : (
        <td
          className="diff-line-widget-old-placeholder select-none p-0"
          style={{ backgroundColor: `var(${emptyBGName})` }}
          colSpan={2}
        >
          {newWidgetRendered && <span>&ensp;</span>}
        </td>
      )}
      {newWidgetRendered ? (
        <td
          className="diff-line-widget-new-content border-l-[1px] p-0"
          colSpan={2}
          style={{ borderLeftColor: `var(${borderColorName})` }}
        >
          <div className="diff-line-widget-wrapper">{newWidgetRendered}</div>
        </td>
      ) : (
        <td
          className="diff-line-widget-new-placeholder select-none border-l-[1px] p-0"
          style={{ backgroundColor: `var(${emptyBGName})`, borderLeftColor: `var(${borderColorName})` }}
          colSpan={2}
        >
          {oldWidgetRendered && <span>&ensp;</span>}
        </td>
      )}
    </tr>
  );
};

export const DiffSplitWidgetLine = ({
  index,
  diffFile,
  lineNumber,
}: {
  index: number;
  diffFile: DiffFile;
  lineNumber: number;
}) => {
  const { useWidget } = useDiffWidgetContext();

  const { widgetLineNumber, widgetSide } = useWidget((s) => ({
    widgetLineNumber: s.widgetLineNumber,
    widgetSide: s.widgetSide,
  }));

  const oldLine = diffFile.getSplitLeftLine(index);

  const newLine = diffFile.getSplitRightLine(index);

  const oldLineWidget = oldLine.lineNumber && widgetSide === SplitSide.old && widgetLineNumber === oldLine.lineNumber;

  const newLineWidget = newLine.lineNumber && widgetSide === SplitSide.new && widgetLineNumber === newLine.lineNumber;

  const currentIsShow = oldLineWidget || newLineWidget;

  if (!currentIsShow) return null;

  return (
    <_DiffSplitWidgetLine
      index={index}
      diffFile={diffFile}
      lineNumber={lineNumber}
      oldLineWidget={oldLineWidget}
      newLineWidget={newLineWidget}
    />
  );
};
