// packages/solid/src/components/DiffWidgetContext.ts
import { createContext, useContext } from "solid-js";

import type { SplitSide } from "..";
import type { Accessor} from "solid-js";

export const DiffWidgetContext = createContext<Accessor<{ side?: SplitSide; lineNumber?: number }>>();

export const useDiffWidgetContext = () => useContext(DiffWidgetContext);

// packages/react/src/components/DiffWidgetContext.ts
import { createContext, useContext } from "react";

import type { SplitSide } from "..";
import type { Ref, UseSelectorWithStore } from "reactivity-store";

export const DiffWidgetContext = createContext<{
  useWidget: UseSelectorWithStore<{
    widgetSide: Ref<SplitSide>;
    widgetLineNumber: Ref<number>;

    setWidget: (props: { side?: SplitSide; lineNumber?: number }) => void;
  }>;
}>(null);

export const useDiffWidgetContext = () => useContext(DiffWidgetContext);
