// packages/vue/src/components/DiffUnifiedExtendLine.tsx
import { computed, defineComponent, ref } from "vue";

import { SplitSide } from "..";
import { useExtendData, useSlots } from "../context";
import { useDomWidth } from "../hooks/useDomWidth";
import { useSubscribeDiffFile } from "../hooks/useSubscribeDiffFile";

import type { DiffFileExtends } from "../utils";

export const DiffUnifiedExtendLine = defineComponent(
  (props: { index: number; diffFile: DiffFileExtends; lineNumber: number }) => {
    const extendData = useExtendData();

    const slots = useSlots();

    const unifiedItem = ref(props.diffFile.getUnifiedLine(props.index));

    const oldExtend = ref(extendData.value?.oldFile?.[unifiedItem.value.oldLineNumber]);

    const newExtend = ref(extendData.value?.newFile?.[unifiedItem.value.newLineNumber]);

    useSubscribeDiffFile(props, (diffFile) => {
      unifiedItem.value = diffFile.getUnifiedLine(props.index);
    });

    useSubscribeDiffFile(props, () => (oldExtend.value = extendData.value?.oldFile?.[unifiedItem.value.oldLineNumber]));

    useSubscribeDiffFile(props, () => (newExtend.value = extendData.value?.newFile?.[unifiedItem.value.newLineNumber]));

    const currentIsShow = computed(() =>
      Boolean((oldExtend.value || newExtend.value) && unifiedItem.value && !unifiedItem.value.isHidden && unifiedItem.value.diff)
    );

    const width = useDomWidth({
      selector: ref(".unified-diff-table-wrapper"),
      enable: currentIsShow,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr data-line={`${props.lineNumber}-extend`} data-state="extend" class="diff-line diff-line-extend">
          <td class="diff-line-extend-content align-top p-0" colspan={4}>
            <div class="diff-line-extend-wrapper sticky left-0" style={{ width: width.value + "px" }}>
              {width.value > 0 &&
                oldExtend.value &&
                slots.extend({
                  diffFile: props.diffFile,
                  side: SplitSide.old,
                  lineNumber: unifiedItem.value.oldLineNumber,
                  data: oldExtend.value.data,
                  onUpdate: props.diffFile.notifyAll,
                })}
              {width.value > 0 &&
                newExtend.value &&
                slots.extend({
                  diffFile: props.diffFile,
                  side: SplitSide.new,
                  lineNumber: unifiedItem.value.newLineNumber,
                  data: newExtend.value.data,
                  onUpdate: props.diffFile.notifyAll,
                })}
            </div>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffUnifiedExtendLine", props: ["diffFile", "index", "lineNumber"] }
);

// packages/react/src/components/DiffUnifiedExtendLine.tsx
import * as React from "react";

import { useDiffViewContext, SplitSide } from "..";
import { useDomWidth } from "../hooks/useDomWidth";

import type { DiffFileExtends } from "../utils";

const _DiffUnifiedExtendLine = ({ index, diffFile, lineNumber }: { index: number; diffFile: DiffFileExtends; lineNumber: number }) => {
  const { extendData, renderExtendLine } = useDiffViewContext();

  const unifiedItem = diffFile.getUnifiedLine(index);

  const oldExtend = extendData?.oldFile?.[unifiedItem.oldLineNumber];

  const newExtend = extendData?.newFile?.[unifiedItem.newLineNumber];

  const width = useDomWidth({
    selector: ".unified-diff-table-wrapper",
    enable: true,
  });

  return (
    <tr data-line={`${lineNumber}-extend`} data-state="extend" className="diff-line diff-line-extend">
      <td className="diff-line-extend-content align-top p-[0]" colSpan={4}>
        <div className="diff-line-extend-wrapper sticky left-0" style={{ width }}>
          {oldExtend &&
            renderExtendLine({ diffFile, side: SplitSide.old, lineNumber: oldExtend.lineNumber, data: oldExtend.data, onUpdate: diffFile.notifyAll })}
          {newExtend &&
            renderExtendLine({ diffFile, side: SplitSide.new, lineNumber: newExtend.lineNumber, data: newExtend.data, onUpdate: diffFile.notifyAll })}
        </div>
      </td>
    </tr>
  );
};

export const DiffUnifiedExtendLine = ({ index, diffFile, lineNumber }: { index: number; diffFile: DiffFileExtends; lineNumber: number }) => {
  const { extendData } = useDiffViewContext();

  const unifiedItem = diffFile.getUnifiedLine(index);

  const oldExtend = extendData?.oldFile?.[unifiedItem.oldLineNumber];

  const newExtend = extendData?.newFile?.[unifiedItem.newLineNumber];

  if ((!oldExtend && !newExtend) || !unifiedItem || unifiedItem.isHidden || !unifiedItem.diff) return null;

  return <_DiffUnifiedExtendLine index={index} diffFile={diffFile} lineNumber={lineNumber} />;
};
