// packages/solid/src/components/DiffUnifiedWidgetLine.tsx
import { SplitSide, type DiffFile } from "@git-diff-view/core";
import { createMemo, Show } from "solid-js";

import { useDomWidth, useEnableWrap, useRenderWidget } from "../hooks";

import { useDiffWidgetContext } from "./DiffWidgetContext";

export const DiffUnifiedWidgetLine = (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
  const renderWidget = useRenderWidget();

  const enableWrap = useEnableWrap();

  const [widget, setWidget] = useDiffWidgetContext() || [];

  const unifiedItem = createMemo(() => props.diffFile.getUnifiedLine(props.index));

  const oldWidget = createMemo(
    () =>
      unifiedItem()?.oldLineNumber &&
      widget?.()?.side === SplitSide.old &&
      widget?.()?.lineNumber === unifiedItem()?.oldLineNumber
  );

  const newWidget = createMemo(
    () =>
      unifiedItem()?.newLineNumber &&
      widget?.()?.side === SplitSide.new &&
      widget?.()?.lineNumber === unifiedItem()?.newLineNumber
  );

  const currentIsHidden = createMemo(() => unifiedItem()?.isHidden);

  const currentIsShow = createMemo(() => !!(oldWidget() || newWidget()) && !currentIsHidden() && !!renderWidget());

  const onCloseWidget = () => setWidget?.({});

  const lineSelector = createMemo(() => `.unified-diff-table-wrapper`);

  const width = useDomWidth({
    selector: lineSelector,
    enable: () => currentIsShow(),
  });

  return (
    <Show when={currentIsShow()}>
      <tr data-line={`${props.lineNumber}-widget`} data-state="widget" class="diff-line diff-line-widget">
        <td class="diff-line-widget-content p-0" colspan={2}>
          <div class="diff-line-widget-wrapper sticky left-0 z-[1]" style={{ width: width() + "px" }}>
            {(enableWrap() ? true : width() > 0) &&
              oldWidget() &&
              renderWidget()?.({
                diffFile: props.diffFile,
                side: SplitSide.old,
                lineNumber: unifiedItem()?.oldLineNumber || 0,
                onClose: onCloseWidget,
              })}
            {(enableWrap() ? true : width() > 0) &&
              newWidget() &&
              renderWidget()?.({
                diffFile: props.diffFile,
                side: SplitSide.new,
                lineNumber: unifiedItem().newLineNumber || 0,
                onClose: onCloseWidget,
              })}
          </div>
        </td>
      </tr>
    </Show>
  );
};

// packages/react/src/components/DiffUnifiedWidgetLine.tsx
import * as React from "react";

import { useDiffViewContext, SplitSide } from "..";
import { useDomWidth } from "../hooks/useDomWidth";

import { useDiffWidgetContext } from "./DiffWidgetContext";

import type { DiffFile } from "@git-diff-view/core";

const _DiffUnifiedWidgetLine = ({ index, diffFile }: { index: number; diffFile: DiffFile; lineNumber: number }) => {
  const unifiedItem = diffFile.getUnifiedLine(index);

  const { widget, setWidget } = useDiffWidgetContext();

  const oldWidget = unifiedItem.oldLineNumber && widget.widgetSide === SplitSide.old && widget.widgetLineNumber === unifiedItem.oldLineNumber;

  const newWidget = unifiedItem.newLineNumber && widget.widgetSide === SplitSide.new && widget.widgetLineNumber === unifiedItem.newLineNumber;

  const onClose = () => setWidget({});

  const { renderWidgetLine } = useDiffViewContext();

  const width = useDomWidth({
    selector: ".unified-diff-table-wrapper",
    enable: true,
  });

  return (
    <tr data-state="widget" className="diff-line diff-line-widget">
      <td className="diff-line-widget-content p-0" colSpan={4}>
        <div className="diff-line-widget-wrapper sticky left-0" style={{ width }}>
          {width > 0 && oldWidget && renderWidgetLine?.({ diffFile, side: SplitSide.old, lineNumber: unifiedItem.oldLineNumber, onClose })}
          {width > 0 && newWidget && renderWidgetLine?.({ diffFile, side: SplitSide.new, lineNumber: unifiedItem.newLineNumber, onClose })}
        </div>
      </td>
    </tr>
  );
};

export const DiffUnifiedWidgetLine = ({ index, diffFile, lineNumber }: { index: number; diffFile: DiffFile; lineNumber: number }) => {
  const { widget } = useDiffWidgetContext();

  const unifiedItem = diffFile.getUnifiedLine(index);

  const oldWidget = unifiedItem.oldLineNumber && widget.widgetSide === SplitSide.old && widget.widgetLineNumber === unifiedItem.oldLineNumber;

  const newWidget = unifiedItem.newLineNumber && widget.widgetSide === SplitSide.new && widget.widgetLineNumber === unifiedItem.newLineNumber;

  const currentIsShow = oldWidget || newWidget;

  if (!currentIsShow) return null;

  return <_DiffUnifiedWidgetLine index={index} diffFile={diffFile} lineNumber={lineNumber} />;
};
