// packages/vue/src/components/DiffSplitContentLineWrap.tsx
import { DiffLineType, type DiffFile, checkDiffLineIncludeChange } from "@git-diff-view/core";
import {
  borderColorName,
  emptyBGName,
  expandLineNumberColorName,
  getContentBG,
  getLineNumberBG,
  plainLineNumberColorName,
} from "@git-diff-view/utils";
import { defineComponent, ref } from "vue";

import { useEnableAddWidget, useEnableHighlight, useOnAddWidgetClick, useSetWidget } from "../context";
import { useSubscribeDiffFile } from "../hooks/useSubscribeDiffFile";

import { DiffSplitAddWidget } from "./DiffAddWidget";
import { DiffContent } from "./DiffContent";
import { SplitSide } from "./DiffView";

export const DiffSplitContentLine = defineComponent(
  (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
    const setWidget = useSetWidget();

    const enableAddWidget = useEnableAddWidget();

    const enableHighlight = useEnableHighlight();

    const onAddWidgetClick = useOnAddWidgetClick();

    const oldLine = ref(props.diffFile.getSplitLeftLine(props.index));

    const newLine = ref(props.diffFile.getSplitRightLine(props.index));

    const oldSyntaxLine = ref(props.diffFile.getOldSyntaxLine(oldLine.value?.lineNumber));

    const newSyntaxLine = ref(props.diffFile.getNewSyntaxLine(newLine.value?.lineNumber));

    const oldPlainLine = ref(props.diffFile.getOldPlainLine(oldLine.value.lineNumber));

    const newPlainLine = ref(props.diffFile.getNewPlainLine(newLine.value.lineNumber));

    const hasDiff = ref(!!oldLine.value?.diff || !!newLine.value?.diff);

    const hasChange = ref(
      checkDiffLineIncludeChange(oldLine.value?.diff) || checkDiffLineIncludeChange(newLine.value?.diff)
    );

    const hasHidden = ref(oldLine.value?.isHidden && newLine.value?.isHidden);

    const oldLineIsDelete = ref(oldLine.value?.diff?.type === DiffLineType.Delete);

    const newLineIsAdded = ref(newLine.value?.diff?.type === DiffLineType.Add);

    useSubscribeDiffFile(props, (diffFile) => {
      oldLine.value = diffFile.getSplitLeftLine(props.index);

      newLine.value = diffFile.getSplitRightLine(props.index);

      oldSyntaxLine.value = diffFile.getOldSyntaxLine(oldLine.value?.lineNumber);

      newSyntaxLine.value = diffFile.getNewSyntaxLine(newLine.value?.lineNumber);

      oldPlainLine.value = diffFile.getOldPlainLine(oldLine.value.lineNumber);

      newPlainLine.value = diffFile.getNewPlainLine(newLine.value.lineNumber);

      hasDiff.value = !!oldLine.value?.diff || !!newLine.value?.diff;

      hasChange.value =
        checkDiffLineIncludeChange(oldLine.value?.diff) || checkDiffLineIncludeChange(newLine.value?.diff);

      hasHidden.value = oldLine.value?.isHidden && newLine.value?.isHidden;

      oldLineIsDelete.value = oldLine.value?.diff?.type === DiffLineType.Delete;

      newLineIsAdded.value = newLine.value?.diff?.type === DiffLineType.Add;
    });

    const onOpenAddWidget = (lineNumber: number, side: SplitSide) => setWidget({ side: side, lineNumber: lineNumber });

    return () => {
      if (hasHidden.value) return null;

      const hasOldLine = !!oldLine.value?.lineNumber;

      const hasNewLine = !!newLine.value?.lineNumber;

      const oldLineContentBG = getContentBG(false, oldLineIsDelete.value, hasDiff.value);

      const oldLineNumberBG = getLineNumberBG(false, oldLineIsDelete.value, hasDiff.value);

      const newLineContentBG = getContentBG(newLineIsAdded.value, false, hasDiff.value);

      const newLineNumberBG = getLineNumberBG(newLineIsAdded.value, false, hasDiff.value);

      return (
        <tr data-line={props.lineNumber} data-state={hasDiff.value ? "diff" : "plain"} class="diff-line">
          {hasOldLine ? (
            <>
              <td
                class="diff-line-old-num group relative w-[1%] min-w-[40px] select-none pl-[10px] pr-[10px] text-right align-top"
                style={{
                  backgroundColor: oldLineNumberBG,
                  color: `var(${hasDiff.value ? plainLineNumberColorName : expandLineNumberColorName})`,
                }}
              >
                {hasDiff.value && enableAddWidget.value && (
                  <DiffSplitAddWidget
                    index={props.index}
                    lineNumber={oldLine.value.lineNumber}
                    side={SplitSide.old}
                    diffFile={props.diffFile}
                    onWidgetClick={onAddWidgetClick}
                    className="absolute left-[100%] z-[1] translate-x-[-50%]"
                    onOpenAddWidget={onOpenAddWidget}
                  />
                )}
                <span data-line-num={oldLine.value.lineNumber} style={{ opacity: hasChange.value ? undefined : 0.5 }}>
                  {oldLine.value.lineNumber}
                </span>
              </td>
              <td
                class="diff-line-old-content group relative pr-[10px] align-top"
                style={{ backgroundColor: oldLineContentBG }}
                data-side={SplitSide[SplitSide.old]}
              >
                {hasDiff.value && enableAddWidget.value && (
                  <DiffSplitAddWidget
                    index={props.index}
                    lineNumber={oldLine.value.lineNumber}
                    side={SplitSide.old}
                    diffFile={props.diffFile}
                    onWidgetClick={onAddWidgetClick}
                    className="absolute right-[100%] z-[1] translate-x-[50%]"
                    onOpenAddWidget={onOpenAddWidget}
                  />
                )}
                <DiffContent
                  enableWrap={true}
                  diffFile={props.diffFile}
                  rawLine={oldLine.value.value}
                  diffLine={oldLine.value.diff}
                  plainLine={oldPlainLine.value}
                  syntaxLine={oldSyntaxLine.value}
                  enableHighlight={enableHighlight.value}
                />
              </td>
            </>
          ) : (
            <td
              class="diff-line-old-placeholder select-none"
              style={{ backgroundColor: `var(${emptyBGName})` }}
              colspan={2}
            >
              <span>&ensp;</span>
            </td>
          )}
          {hasNewLine ? (
            <>
              <td
                class="diff-line-new-num group relative w-[1%] min-w-[40px] select-none border-l-[1px] pl-[10px] pr-[10px] text-right align-top"
                style={{
                  backgroundColor: newLineNumberBG,
                  color: `var(${hasDiff.value ? plainLineNumberColorName : expandLineNumberColorName})`,
                  borderLeftColor: `var(${borderColorName})`,
                  borderLeftStyle: "solid",
                }}
              >
                {hasDiff.value && enableAddWidget.value && (
                  <DiffSplitAddWidget
                    index={props.index}
                    lineNumber={newLine.value.lineNumber}
                    side={SplitSide.new}
                    diffFile={props.diffFile}
                    onWidgetClick={onAddWidgetClick}
                    className="absolute left-[100%] z-[1] translate-x-[-50%]"
                    onOpenAddWidget={onOpenAddWidget}
                  />
                )}
                <span data-line-num={newLine.value.lineNumber} style={{ opacity: hasChange.value ? undefined : 0.5 }}>
                  {newLine.value.lineNumber}
                </span>
              </td>
              <td
                class="diff-line-new-content group relative pr-[10px] align-top"
                style={{ backgroundColor: newLineContentBG }}
                data-side={SplitSide[SplitSide.new]}
              >
                {hasDiff.value && enableAddWidget.value && (
                  <DiffSplitAddWidget
                    index={props.index}
                    lineNumber={newLine.value.lineNumber}
                    side={SplitSide.new}
                    diffFile={props.diffFile}
                    onWidgetClick={onAddWidgetClick}
                    className="absolute right-[100%] z-[1] translate-x-[50%]"
                    onOpenAddWidget={onOpenAddWidget}
                  />
                )}
                <DiffContent
                  enableWrap={true}
                  diffFile={props.diffFile}
                  rawLine={newLine.value.value || ""}
                  diffLine={newLine.value.diff}
                  plainLine={newPlainLine.value}
                  syntaxLine={newSyntaxLine.value}
                  enableHighlight={enableHighlight.value}
                />
              </td>
            </>
          ) : (
            <td
              class="diff-line-new-placeholder select-none border-l-[1px]"
              style={{
                backgroundColor: `var(${emptyBGName})`,
                borderLeftColor: `var(${borderColorName})`,
                borderLeftStyle: "solid",
              }}
              colspan={2}
            >
              <span>&ensp;</span>
            </td>
          )}
        </tr>
      );
    };
  },
  { name: "DiffSplitContentLine", props: ["diffFile", "index", "lineNumber"] }
);

// packages/react/src/components/DiffSplitContentLineWrap.tsx
import { DiffLineType, type DiffFile, checkDiffLineIncludeChange } from "@git-diff-view/core";
import {
  getContentBG,
  getLineNumberBG,
  plainLineNumberColorName,
  emptyBGName,
  borderColorName,
  expandLineNumberColorName,
} from "@git-diff-view/utils";
import * as React from "react";

import { SplitSide } from "..";

import { DiffSplitAddWidget } from "./DiffAddWidget";
import { DiffContent } from "./DiffContent";
import { useDiffViewContext } from "./DiffViewContext";
import { useDiffWidgetContext } from "./DiffWidgetContext";

const InternalDiffSplitLine = ({
  index,
  diffFile,
  lineNumber,
  enableAddWidget,
  enableHighlight,
}: {
  index: number;
  diffFile: DiffFile;
  lineNumber: number;
  enableHighlight: boolean;
  enableAddWidget: boolean;
}) => {
  const oldLine = diffFile.getSplitLeftLine(index);

  const newLine = diffFile.getSplitRightLine(index);

  const oldSyntaxLine = diffFile.getOldSyntaxLine(oldLine?.lineNumber);

  const oldPlainLine = diffFile.getOldPlainLine(oldLine.lineNumber);

  const newSyntaxLine = diffFile.getNewSyntaxLine(newLine?.lineNumber);

  const newPlainLine = diffFile.getNewPlainLine(newLine.lineNumber);

  const hasDiff = !!oldLine?.diff || !!newLine?.diff;

  const hasChange = checkDiffLineIncludeChange(oldLine?.diff) || checkDiffLineIncludeChange(newLine?.diff);

  const oldLineIsDelete = oldLine?.diff?.type === DiffLineType.Delete;

  const newLineIsAdded = newLine?.diff?.type === DiffLineType.Add;

  const { useDiffContext } = useDiffViewContext();

  const onAddWidgetClick = useDiffContext.getReadonlyState().onAddWidgetClick;

  const { useWidget } = useDiffWidgetContext();

  const setWidget = useWidget.getReadonlyState().setWidget;

  const hasOldLine = !!oldLine.lineNumber;

  const hasNewLine = !!newLine.lineNumber;

  const oldLineContentBG = getContentBG(false, oldLineIsDelete, hasDiff);

  const oldLineNumberBG = getLineNumberBG(false, oldLineIsDelete, hasDiff);

  const newLineContentBG = getContentBG(newLineIsAdded, false, hasDiff);

  const newLineNumberBG = getLineNumberBG(newLineIsAdded, false, hasDiff);

  return (
    <tr data-line={lineNumber} data-state={hasDiff ? "diff" : "plain"} className="diff-line">
      {hasOldLine ? (
        <>
          <td
            className="diff-line-old-num group relative w-[1%] min-w-[40px] select-none pl-[10px] pr-[10px] text-right align-top"
            data-side={SplitSide[SplitSide.old]}
            style={{
              backgroundColor: oldLineNumberBG,
              color: `var(${hasDiff ? plainLineNumberColorName : expandLineNumberColorName})`,
            }}
          >
            {hasDiff && enableAddWidget && (
              <DiffSplitAddWidget
                index={index}
                lineNumber={oldLine.lineNumber}
                side={SplitSide.old}
                diffFile={diffFile}
                onWidgetClick={(...props) => onAddWidgetClick.current?.(...props)}
                className="absolute left-[100%] z-[1] translate-x-[-50%]"
                onOpenAddWidget={(lineNumber, side) => setWidget({ lineNumber: lineNumber, side: side })}
              />
            )}
            <span data-line-num={oldLine.lineNumber} style={{ opacity: hasChange ? undefined : 0.5 }}>
              {oldLine.lineNumber}
            </span>
          </td>
          <td
            className="diff-line-old-content group relative pr-[10px] align-top"
            data-side={SplitSide[SplitSide.old]}
            style={{ backgroundColor: oldLineContentBG }}
          >
            {hasDiff && enableAddWidget && (
              <DiffSplitAddWidget
                index={index}
                lineNumber={oldLine.lineNumber}
                side={SplitSide.old}
                diffFile={diffFile}
                onWidgetClick={(...props) => onAddWidgetClick.current?.(...props)}
                className="absolute right-[100%] z-[1] translate-x-[50%]"
                onOpenAddWidget={(lineNumber, side) => setWidget({ lineNumber: lineNumber, side: side })}
              />
            )}
            <DiffContent
              enableWrap={true}
              diffFile={diffFile}
              rawLine={oldLine.value}
              diffLine={oldLine.diff}
              plainLine={oldPlainLine}
              syntaxLine={oldSyntaxLine}
              enableHighlight={enableHighlight}
            />
          </td>
        </>
      ) : (
        <td
          className="diff-line-old-placeholder select-none"
          data-side={SplitSide[SplitSide.old]}
          style={{ backgroundColor: `var(${emptyBGName})` }}
          colSpan={2}
        >
          <span>&ensp;</span>
        </td>
      )}
      {hasNewLine ? (
        <>
          <td
            className="diff-line-new-num group relative w-[1%] min-w-[40px] select-none border-l-[1px] pl-[10px] pr-[10px] text-right align-top"
            data-side={SplitSide[SplitSide.new]}
            style={{
              backgroundColor: newLineNumberBG,
              color: `var(${hasDiff ? plainLineNumberColorName : expandLineNumberColorName})`,
              borderLeftColor: `var(${borderColorName})`,
              borderLeftStyle: "solid",
            }}
          >
            {hasDiff && enableAddWidget && (
              <DiffSplitAddWidget
                index={index}
                lineNumber={newLine.lineNumber}
                side={SplitSide.new}
                diffFile={diffFile}
                onWidgetClick={(...props) => onAddWidgetClick.current?.(...props)}
                className="absolute left-[100%] z-[1] translate-x-[-50%]"
                onOpenAddWidget={(lineNumber, side) => setWidget({ lineNumber: lineNumber, side: side })}
              />
            )}
            <span data-line-num={newLine.lineNumber} style={{ opacity: hasChange ? undefined : 0.5 }}>
              {newLine.lineNumber}
            </span>
          </td>
          <td
            className="diff-line-new-content group relative pr-[10px] align-top"
            data-side={SplitSide[SplitSide.new]}
            style={{ backgroundColor: newLineContentBG }}
          >
            {hasDiff && enableAddWidget && (
              <DiffSplitAddWidget
                index={index}
                lineNumber={newLine.lineNumber}
                side={SplitSide.new}
                diffFile={diffFile}
                onWidgetClick={(...props) => onAddWidgetClick.current?.(...props)}
                className="absolute right-[100%] z-[1] translate-x-[50%]"
                onOpenAddWidget={(lineNumber, side) => setWidget({ lineNumber: lineNumber, side: side })}
              />
            )}
            <DiffContent
              enableWrap={true}
              diffFile={diffFile}
              rawLine={newLine.value || ""}
              diffLine={newLine.diff}
              plainLine={newPlainLine}
              syntaxLine={newSyntaxLine}
              enableHighlight={enableHighlight}
            />
          </td>
        </>
      ) : (
        <td
          className="diff-line-new-placeholder select-none border-l-[1px]"
          style={{
            backgroundColor: `var(${emptyBGName})`,
            borderLeftColor: `var(${borderColorName})`,
            borderLeftStyle: "solid",
          }}
          data-side={SplitSide[SplitSide.new]}
          colSpan={2}
        >
          <span>&ensp;</span>
        </td>
      )}
    </tr>
  );
};

export const DiffSplitContentLine = ({
  index,
  diffFile,
  lineNumber,
  enableAddWidget,
  enableHighlight,
}: {
  index: number;
  diffFile: DiffFile;
  lineNumber: number;
  enableHighlight: boolean;
  enableAddWidget: boolean;
}) => {
  const oldLine = diffFile.getSplitLeftLine(index);

  const newLine = diffFile.getSplitRightLine(index);

  if (oldLine?.isHidden && newLine?.isHidden) return null;

  return (
    <InternalDiffSplitLine
      index={index}
      diffFile={diffFile}
      lineNumber={lineNumber}
      enableAddWidget={enableAddWidget}
      enableHighlight={enableHighlight}
    />
  );
};
