// packages/react/src/components/DiffContent.tsx
/* eslint-disable max-lines */
import {
  DiffLineType,
  getSyntaxDiffTemplate,
  getSyntaxLineTemplate,
  getPlainDiffTemplate,
  getPlainLineTemplate,
} from "@git-diff-view/core";
import {
  memoFunc,
  addContentHighlightBGName,
  delContentHighlightBGName,
  diffFontSizeName,
  getSymbol,
  NewLineSymbol,
} from "@git-diff-view/utils";
import * as React from "react";

import { DiffNoNewLine } from "./DiffNoNewLine";

import type { DiffFile, DiffLine, File } from "@git-diff-view/core";

const temp = {};

const formatStringToCamelCase = (str: string) => {
  if (str.startsWith("--")) return str;
  const splitted = str.split("-");
  if (splitted.length === 1) return splitted[0];
  return (
    splitted[0] +
    splitted
      .slice(1)
      .map((word) => word[0].toUpperCase() + word.slice(1))
      .join("")
  );
};

export const getStyleObjectFromString = memoFunc((str: string) => {
  if (!str) return temp;
  const style = {};
  str.split(";").forEach((el) => {
    const [property, value] = el.split(":");
    if (!property) return;

    const formattedProperty = formatStringToCamelCase(property.trim());
    style[formattedProperty] = value.trim();
  });
  return style;
});

const DiffString = ({
  rawLine,
  diffLine,
  operator,
  plainLine,
  enableWrap,
  enableTemplate,
}: {
  rawLine: string;
  diffLine?: DiffLine;
  operator?: "add" | "del";
  plainLine?: File["plainFile"][number];
  enableWrap?: boolean;
  enableTemplate?: boolean;
}) => {
  const changes = diffLine?.changes;

  if (changes?.hasLineChange) {
    const isNewLineSymbolChanged = changes.newLineSymbol;

    if (enableTemplate && !diffLine?.plainTemplate && typeof getPlainDiffTemplate === "function") {
      getPlainDiffTemplate({ diffLine, rawLine, operator });
    }

    if (enableTemplate && diffLine?.plainTemplate) {
      return (
        <span className="diff-line-content-raw">
          <span data-template dangerouslySetInnerHTML={{ __html: diffLine.plainTemplate }} />
          {isNewLineSymbolChanged === NewLineSymbol.NEWLINE && (
            <span
              data-no-newline-at-end-of-file-symbol
              className={enableWrap ? "block !text-red-500" : "inline-block align-middle !text-red-500"}
              style={{
                width: `var(${diffFontSizeName})`,
                height: `var(${diffFontSizeName})`,
              }}
            >
              <DiffNoNewLine />
            </span>
          )}
        </span>
      );
    } else {
      // TODO remove
      const range = changes.range;
      const str1 = rawLine.slice(0, range.location);
      const str2 = rawLine.slice(range.location, range.location + range.length);
      const str3 = rawLine.slice(range.location + range.length);
      const isLast = str2.includes("\n");
      const _str2 = isLast ? str2.replace("\n", "").replace("\r", "") : str2;
      return (
        <span className="diff-line-content-raw">
          <span data-range-start={range.location} data-range-end={range.location + range.length}>
            {str1}
            <span
              data-diff-highlight
              className="rounded-[0.2em]"
              style={{
                backgroundColor:
                  operator === "add" ? `var(${addContentHighlightBGName})` : `var(${delContentHighlightBGName})`,
              }}
            >
              {isLast ? (
                <>
                  {_str2}
                  <span data-newline-symbol>{getSymbol(isNewLineSymbolChanged)}</span>
                </>
              ) : (
                str2
              )}
            </span>
            {str3}
          </span>
          {isNewLineSymbolChanged === NewLineSymbol.NEWLINE && (
            <span
              data-no-newline-at-end-of-file-symbol
              className={enableWrap ? "block !text-red-500" : "inline-block align-middle !text-red-500"}
              style={{
                width: `var(${diffFontSizeName})`,
                height: `var(${diffFontSizeName})`,
              }}
            >
              <DiffNoNewLine />
            </span>
          )}
        </span>
      );
    }
  }

  if (enableTemplate && plainLine && !plainLine?.template) {
    plainLine.template = getPlainLineTemplate(plainLine.value);
  }

  if (enableTemplate && plainLine?.template) {
    return (
      <span className="diff-line-content-raw">
        <span data-template dangerouslySetInnerHTML={{ __html: plainLine.template }} />
      </span>
    );
  }

  return <span className="diff-line-content-raw">{rawLine}</span>;
};

const DiffSyntax = ({
  rawLine,
  diffLine,
  operator,
  syntaxLine,
  enableWrap,
  enableTemplate,
}: {
  rawLine: string;
  diffLine?: DiffLine;
  syntaxLine?: File["syntaxFile"][number];
  operator?: "add" | "del";
  enableWrap?: boolean;
  enableTemplate?: boolean;
}) => {
  if (!syntaxLine) {
    return <DiffString rawLine={rawLine} diffLine={diffLine} operator={operator} enableTemplate={enableTemplate} />;
  }

  const changes = diffLine?.changes;

  if (changes?.hasLineChange) {
    const isNewLineSymbolChanged = changes.newLineSymbol;

    if (enableTemplate && !diffLine?.syntaxTemplate && typeof getSyntaxDiffTemplate === "function") {
      getSyntaxDiffTemplate({ diffLine, syntaxLine, operator });
    }

    if (enableTemplate && diffLine?.syntaxTemplate) {
      return (
        <span className="diff-line-syntax-raw">
          <span data-template dangerouslySetInnerHTML={{ __html: diffLine.syntaxTemplate }} />
          {isNewLineSymbolChanged === NewLineSymbol.NEWLINE && (
            <span
              data-no-newline-at-end-of-file-symbol
              className={enableWrap ? "block !text-red-500" : "inline-block align-middle !text-red-500"}
              style={{
                width: `var(${diffFontSizeName})`,
                height: `var(${diffFontSizeName})`,
              }}
            >
              <DiffNoNewLine />
            </span>
          )}
        </span>
      );
    } else {
      // TODO remove
      const range = changes.range;

      return (
        <span className="diff-line-syntax-raw">
          <span data-range-start={range.location} data-range-end={range.location + range.length}>
            {syntaxLine.nodeList?.map(({ node, wrapper }, index) => {
              if (node.endIndex < range.location || range.location + range.length < node.startIndex) {
                return (
                  <span
                    key={index}
                    data-start={node.startIndex}
                    data-end={node.endIndex}
                    className={wrapper?.properties?.className?.join(" ")}
                    style={getStyleObjectFromString(wrapper?.properties?.style || "")}
                  >
                    {node.value}
                  </span>
                );
              } else {
                const index1 = range.location - node.startIndex;
                const index2 = index1 < 0 ? 0 : index1;
                const str1 = node.value.slice(0, index2);
                const str2 = node.value.slice(index2, index1 + range.length);
                const str3 = node.value.slice(index1 + range.length);
                const isStart = str1.length || range.location === node.startIndex;
                const isEnd = str3.length || node.endIndex === range.location + range.length - 1;
                const isLast = str2.includes("\n");
                const _str2 = isLast ? str2.replace("\n", "").replace("\r", "") : str2;
                return (
                  <span
                    key={index}
                    data-start={node.startIndex}
                    data-end={node.endIndex}
                    className={wrapper?.properties?.className?.join(" ")}
                    style={getStyleObjectFromString(wrapper?.properties?.style || "")}
                  >
                    {str1}
                    <span
                      data-diff-highlight
                      style={{
                        backgroundColor:
                          operator === "add"
                            ? `var(${addContentHighlightBGName})`
                            : `var(${delContentHighlightBGName})`,
                        borderTopLeftRadius: isStart ? "0.2em" : undefined,
                        borderBottomLeftRadius: isStart ? "0.2em" : undefined,
                        borderTopRightRadius: isEnd || isLast ? "0.2em" : undefined,
                        borderBottomRightRadius: isEnd || isLast ? "0.2em" : undefined,
                      }}
                    >
                      {isLast ? (
                        <>
                          {_str2}
                          <span data-newline-symbol>{getSymbol(isNewLineSymbolChanged)}</span>
                        </>
                      ) : (
                        str2
                      )}
                    </span>
                    {str3}
                  </span>
                );
              }
            })}
          </span>
          {isNewLineSymbolChanged === NewLineSymbol.NEWLINE && (
            <span
              data-no-newline-at-end-of-file-symbol
              className={enableWrap ? "block !text-red-500" : "inline-block align-middle !text-red-500"}
              style={{
                width: `var(${diffFontSizeName})`,
                height: `var(${diffFontSizeName})`,
              }}
            >
              <DiffNoNewLine />
            </span>
          )}
        </span>
      );
    }
  }

  if (enableTemplate && !syntaxLine.template) {
    syntaxLine.template = getSyntaxLineTemplate(syntaxLine);
  }

  if (enableTemplate && syntaxLine?.template) {
    return (
      <span className="diff-line-syntax-raw">
        <span data-template dangerouslySetInnerHTML={{ __html: syntaxLine.template }} />
      </span>
    );
  }

  return (
    <span className="diff-line-syntax-raw">
      {syntaxLine?.nodeList?.map(({ node, wrapper }, index) => (
        <span
          key={index}
          data-start={node.startIndex}
          data-end={node.endIndex}
          className={wrapper?.properties?.className?.join(" ")}
          style={getStyleObjectFromString(wrapper?.properties?.style || "")}
        >
          {node.value}
        </span>
      ))}
    </span>
  );
};

export const DiffContent = ({
  diffLine,
  diffFile,
  rawLine,
  plainLine,
  syntaxLine,
  enableWrap,
  enableHighlight,
}: {
  rawLine: string;
  plainLine?: File["plainFile"][number];
  syntaxLine?: File["syntaxFile"][number];
  diffLine?: DiffLine;
  diffFile: DiffFile;
  enableWrap: boolean;
  enableHighlight: boolean;
}) => {
  const isAdded = diffLine?.type === DiffLineType.Add;

  const isDelete = diffLine?.type === DiffLineType.Delete;

  const isMaxLineLengthToIgnoreSyntax = syntaxLine?.nodeList?.length > 150;

  const isEnableTemplate = diffFile.getIsEnableTemplate?.() ?? true;

  return (
    <div
      className="diff-line-content-item pl-[2.0em]"
      // data-val={rawLine}
      style={{
        whiteSpace: enableWrap ? "pre-wrap" : "pre",
        wordBreak: enableWrap ? "break-all" : "initial",
      }}
    >
      <span
        data-operator={isAdded ? "+" : isDelete ? "-" : undefined}
        className="diff-line-content-operator ml-[-1.5em] inline-block w-[1.5em] select-none indent-[0.2em]"
      >
        {isAdded ? "+" : isDelete ? "-" : " "}
      </span>
      {enableHighlight && syntaxLine && !isMaxLineLengthToIgnoreSyntax ? (
        <DiffSyntax
          operator={isAdded ? "add" : isDelete ? "del" : undefined}
          rawLine={rawLine}
          diffLine={diffLine}
          syntaxLine={syntaxLine}
          enableWrap={enableWrap}
          enableTemplate={isEnableTemplate}
        />
      ) : (
        <DiffString
          operator={isAdded ? "add" : isDelete ? "del" : undefined}
          rawLine={rawLine}
          diffLine={diffLine}
          plainLine={plainLine}
          enableWrap={enableWrap}
          enableTemplate={isEnableTemplate}
        />
      )}
    </div>
  );
};

// packages/solid/src/components/DiffContent.tsx
import {
  DiffLineType,
  getSyntaxDiffTemplate,
  type File,
  type DiffFile,
  type DiffLine,
  getSyntaxLineTemplate,
  getPlainDiffTemplate,
  getPlainLineTemplate,
} from "@git-diff-view/core";
import {
  addContentHighlightBGName,
  delContentHighlightBGName,
  diffFontSizeName,
  getSymbol,
  NewLineSymbol,
} from "@git-diff-view/utils";
import { createMemo, For, Show } from "solid-js";

import { DiffNoNewLine } from "./DiffNoNewLine";

const DiffString = (props: {
  rawLine: string;
  diffLine?: DiffLine;
  operator?: "add" | "del";
  plainLine?: File["plainFile"][number];
  enableWrap?: boolean;
  enableTemplate?: boolean;
}) => {
  const getIsNewLineSymbolChanged = () => props.diffLine?.changes?.newLineSymbol;

  const initTemplateIfNeed = () => {
    if (
      props.enableTemplate &&
      props.operator &&
      props.diffLine &&
      !props.diffLine?.plainTemplate &&
      typeof getPlainDiffTemplate === "function"
    ) {
      getPlainDiffTemplate({ diffLine: props.diffLine, rawLine: props.rawLine, operator: props.operator });
    }

    if (props.enableTemplate && props.plainLine && !props.plainLine.template) {
      props.plainLine.template = getPlainLineTemplate(props.plainLine.value);
    }
  };

  // eslint-disable-next-line solid/reactivity
  createMemo(initTemplateIfNeed);

  return (
    <Show
      when={props.diffLine?.changes?.hasLineChange}
      fallback={
        <Show
          when={props.enableTemplate && props.plainLine?.template}
          fallback={<span class="diff-line-content-raw">{props.rawLine}</span>}
        >
          <span class="diff-line-content-raw">
            {/* eslint-disable-next-line solid/no-innerhtml */}
            <span data-template innerHTML={props.plainLine?.template} />
          </span>
        </Show>
      }
    >
      <Show
        when={props.enableTemplate && props.diffLine?.plainTemplate}
        fallback={(function () {
          const range = props.diffLine?.changes?.range;
          const str1 = props.rawLine.slice(0, range?.location);
          const str2 = props.rawLine.slice(range?.location, (range?.location || 0) + (range?.length || 0));
          const str3 = props.rawLine.slice((range?.location || 0) + (range?.length || 0));
          const isLast = str2.includes("\n");
          const _str2 = isLast ? str2.replace("\n", "").replace("\r", "") : str2;
          return (
            <span class="diff-line-content-raw">
              <span data-range-start={range?.location} data-range-end={(range?.location || 0) + (range?.length || 0)}>
                {str1}
                <span
                  data-diff-highlight
                  class="rounded-[0.2em]"
                  style={{
                    "background-color":
                      props.operator === "add"
                        ? `var(${addContentHighlightBGName})`
                        : `var(${delContentHighlightBGName})`,
                  }}
                >
                  {isLast ? (
                    <>
                      {_str2}
                      <span data-newline-symbol>{getSymbol(getIsNewLineSymbolChanged())}</span>
                    </>
                  ) : (
                    str2
                  )}
                </span>
                {str3}
              </span>
              {getIsNewLineSymbolChanged() === NewLineSymbol.NEWLINE && (
                <span
                  data-no-newline-at-end-of-file-symbol
                  class={props.enableWrap ? "block !text-red-500" : "inline-block align-middle !text-red-500"}
                  style={{
                    width: `var(${diffFontSizeName})`,
                    height: `var(${diffFontSizeName})`,
                  }}
                >
                  <DiffNoNewLine />
                </span>
              )}
            </span>
          );
        })()}
      >
        <span class="diff-line-content-raw">
          {/* eslint-disable-next-line solid/no-innerhtml */}
          <span data-template innerHTML={props.diffLine?.plainTemplate} />
          {getIsNewLineSymbolChanged() === NewLineSymbol.NEWLINE && (
            <span
              data-no-newline-at-end-of-file-symbol
              class={props.enableWrap ? "block !text-red-500" : "inline-block align-middle !text-red-500"}
              style={{
                width: `var(${diffFontSizeName})`,
                height: `var(${diffFontSizeName})`,
              }}
            >
              <DiffNoNewLine />
            </span>
          )}
        </span>
      </Show>
    </Show>
  );
};

const DiffSyntax = (props: {
  rawLine: string;
  diffLine?: DiffLine;
  syntaxLine?: File["syntaxFile"][number];
  operator?: "add" | "del";
  enableWrap?: boolean;
  enableTemplate?: boolean;
}) => {
  const getRange = () => props.diffLine?.changes?.range;

  const getIsNewLineSymbolChanged = () => props.diffLine?.changes?.newLineSymbol;

  const initTemplateIfNeed = () => {
    if (
      props.enableTemplate &&
      props.diffLine &&
      props.syntaxLine &&
      props.operator &&
      !props.diffLine?.syntaxTemplate &&
      typeof getSyntaxDiffTemplate === "function"
    ) {
      getSyntaxDiffTemplate({ diffLine: props.diffLine, syntaxLine: props.syntaxLine, operator: props.operator });
    }

    if (props.enableTemplate && props.syntaxLine && !props.syntaxLine?.template) {
      props.syntaxLine.template = getSyntaxLineTemplate(props.syntaxLine);
    }
  };

  // eslint-disable-next-line solid/reactivity
  createMemo(initTemplateIfNeed);

  return (
    <Show
      when={props.syntaxLine}
      fallback={
        <DiffString
          rawLine={props.rawLine}
          diffLine={props.diffLine}
          operator={props.operator}
          enableWrap={props.enableWrap}
          enableTemplate={props.enableTemplate}
        />
      }
    >
      <Show
        when={props.diffLine?.changes?.hasLineChange}
        fallback={
          <Show
            when={props.enableTemplate && props.syntaxLine?.template}
            fallback={
              <span class="diff-line-syntax-raw">
                <For each={props.syntaxLine?.nodeList || []}>
                  {({ node, wrapper }) => (
                    <span
                      data-start={node.startIndex}
                      data-end={node.endIndex}
                      class={wrapper?.properties?.className?.join(" ")}
                      style={wrapper?.properties?.style}
                    >
                      {node.value}
                    </span>
                  )}
                </For>
              </span>
            }
          >
            <span class="diff-line-syntax-raw">
              {/* eslint-disable-next-line solid/no-innerhtml */}
              <span data-template innerHTML={props.syntaxLine?.template} />
            </span>
          </Show>
        }
      >
        <Show
          when={props.enableTemplate && props.diffLine?.syntaxTemplate}
          fallback={
            <span class="diff-line-syntax-raw">
              <span
                data-range-start={getRange()?.location}
                data-range-end={(getRange()?.location || 0) + (getRange()?.length || 0)}
              >
                <For each={props.syntaxLine?.nodeList}>
                  {({ node, wrapper }) => {
                    if (
                      node.endIndex < getRange()!.location ||
                      getRange()!.location + getRange()!.length < node.startIndex
                    ) {
                      return (
                        <span
                          data-start={node.startIndex}
                          data-end={node.endIndex}
                          class={wrapper?.properties?.className?.join(" ")}
                          style={wrapper?.properties?.style}
                        >
                          {node.value}
                        </span>
                      );
                    } else {
                      const index1 = getRange()!.location - node.startIndex;
                      const index2 = index1 < 0 ? 0 : index1;
                      const str1 = node.value.slice(0, index2);
                      const str2 = node.value.slice(index2, index1 + getRange()!.length);
                      const str3 = node.value.slice(index1 + getRange()!.length);
                      const isStart = str1.length || getRange()!.location === node.startIndex;
                      const isEnd = str3.length || node.endIndex === getRange()!.location + getRange()!.length - 1;
                      const isLast = str2.includes("\n");
                      const _str2 = isLast ? str2.replace("\n", "").replace("\r", "") : str2;
                      return (
                        <span
                          data-start={node.startIndex}
                          data-end={node.endIndex}
                          class={wrapper?.properties?.className?.join(" ")}
                          style={wrapper?.properties?.style}
                        >
                          {str1}
                          <span
                            data-diff-highlight
                            style={{
                              "background-color":
                                props.operator === "add"
                                  ? `var(${addContentHighlightBGName})`
                                  : `var(${delContentHighlightBGName})`,
                              "border-top-left-radius": isStart ? "0.2em" : undefined,
                              "border-bottom-left-radius": isStart ? "0.2em" : undefined,
                              "border-top-right-radius": isEnd || isLast ? "0.2em" : undefined,
                              "border-bottom-right-radius": isEnd || isLast ? "0.2em" : undefined,
                            }}
                          >
                            {isLast ? (
                              <>
                                {_str2}
                                <span data-newline-symbol>{getSymbol(getIsNewLineSymbolChanged())}</span>
                              </>
                            ) : (
                              str2
                            )}
                          </span>
                          {str3}
                        </span>
                      );
                    }
                  }}
                </For>
              </span>
              {getIsNewLineSymbolChanged() === NewLineSymbol.NEWLINE && (
                <span
                  data-no-newline-at-end-of-file-symbol
                  class={props.enableWrap ? "block !text-red-500" : "inline-block align-middle !text-red-500"}
                  style={{
                    width: `var(${diffFontSizeName})`,
                    height: `var(${diffFontSizeName})`,
                  }}
                >
                  <DiffNoNewLine />
                </span>
              )}
            </span>
          }
        >
          <span class="diff-line-syntax-raw">
            {/* eslint-disable-next-line solid/no-innerhtml */}
            <span data-template innerHTML={props.diffLine?.syntaxTemplate} />
            {getIsNewLineSymbolChanged() === NewLineSymbol.NEWLINE && (
              <span
                data-no-newline-at-end-of-file-symbol
                class={props.enableWrap ? "block !text-red-500" : "inline-block align-middle !text-red-500"}
                style={{
                  width: `var(${diffFontSizeName})`,
                  height: `var(${diffFontSizeName})`,
                }}
              >
                <DiffNoNewLine />
              </span>
            )}
          </span>
        </Show>
      </Show>
    </Show>
  );
};

export const DiffContent = (props: {
  rawLine: string;
  plainLine?: File["plainFile"][number];
  syntaxLine?: File["syntaxFile"][number];
  diffLine?: DiffLine;
  diffFile: DiffFile;
  enableWrap: boolean;
  enableHighlight: boolean;
}) => {
  const getIsAdded = () => props.diffLine?.type === DiffLineType.Add;

  const getIsDelete = () => props.diffLine?.type === DiffLineType.Delete;

  const getIsMaxLineLengthToIgnoreSyntax = () =>
    props.syntaxLine?.nodeList ? props.syntaxLine?.nodeList?.length > 150 : false;

  const getIsEnableTemplate = () => props.diffFile.getIsEnableTemplate?.() ?? true;

  return (
    <div
      class="diff-line-content-item pl-[2.0em]"
      style={{
        "white-space": props.enableWrap ? "pre-wrap" : "pre",
        "word-break": props.enableWrap ? "break-all" : "initial",
      }}
    >
      <span
        data-operator={getIsAdded() ? "+" : getIsDelete() ? "-" : undefined}
        class="diff-line-content-operator ml-[-1.5em] inline-block w-[1.5em] select-none indent-[0.2em]"
      >
        {getIsAdded() ? "+" : getIsDelete() ? "-" : " "}
      </span>
      {props.enableHighlight && props.syntaxLine && !getIsMaxLineLengthToIgnoreSyntax() ? (
        <DiffSyntax
          operator={getIsAdded() ? "add" : getIsDelete() ? "del" : undefined}
          rawLine={props.rawLine}
          diffLine={props.diffLine}
          syntaxLine={props.syntaxLine}
          enableWrap={props.enableWrap}
          enableTemplate={getIsEnableTemplate()}
        />
      ) : (
        <DiffString
          operator={getIsAdded() ? "add" : getIsDelete() ? "del" : undefined}
          rawLine={props.rawLine}
          diffLine={props.diffLine}
          plainLine={props.plainLine}
          enableWrap={props.enableWrap}
          enableTemplate={getIsEnableTemplate()}
        />
      )}
    </div>
  );
};
