// packages/react/src/components/DiffView.tsx
/* eslint-disable @typescript-eslint/no-unnecessary-type-constraint */
/* eslint-disable @typescript-eslint/ban-ts-comment */
import { DiffFile, _cacheMap } from "@git-diff-view/core";
import { memo, useEffect, useMemo, forwardRef, useImperativeHandle, useRef } from "react";
import * as React from "react";

import { useUnmount } from "../hooks/useUnmount";

import { DiffSplitView } from "./DiffSplitView";
import { DiffUnifiedView } from "./DiffUnifiedView";
import { DiffModeEnum, DiffViewContext } from "./DiffViewContext";
import { createDiffConfigStore, diffFontSizeName } from "./tools";
// import { DiffSplitView } from "./v2/DiffSplitView_v2";

import type { DiffHighlighter, DiffHighlighterLang } from "@git-diff-view/core";
import type { CSSProperties, ForwardedRef, ReactNode } from "react";

_cacheMap.name = "@git-diff-view/react";

export enum SplitSide {
  old = 1,
  new = 2,
}

export type DiffViewProps<T> = {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | string | null; content?: string | null };
    hunks: string[];
  };
  extendData?: { oldFile?: Record<string, { data: T }>; newFile?: Record<string, { data: T }> };
  diffFile?: DiffFile;
  className?: string;
  style?: CSSProperties;
  /**
   * provide a custom highlighter
   * eg: lowlight, refractor, starry-night, shiki
   */
  registerHighlighter?: Omit<DiffHighlighter, "getHighlighterEngine">;
  diffViewMode?: DiffModeEnum;
  diffViewWrap?: boolean;
  diffViewTheme?: "light" | "dark";
  diffViewFontSize?: number;
  diffViewHighlight?: boolean;
  diffViewAddWidget?: boolean;
  renderWidgetLine?: ({
    diffFile,
    side,
    lineNumber,
    onClose,
  }: {
    lineNumber: number;
    side: SplitSide;
    diffFile: DiffFile;
    onClose: () => void;
  }) => ReactNode;
  renderExtendLine?: ({
    diffFile,
    side,
    data,
    lineNumber,
    onUpdate,
  }: {
    lineNumber: number;
    side: SplitSide;
    data: T;
    diffFile: DiffFile;
    onUpdate: () => void;
  }) => ReactNode;
  onAddWidgetClick?: (lineNumber: number, side: SplitSide) => void;
};

type DiffViewProps_1<T> = Omit<DiffViewProps<T>, "data"> & {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | null; content?: string | null };
    hunks: string[];
  };
};

type DiffViewProps_2<T> = Omit<DiffViewProps<T>, "data"> & {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    hunks: string[];
  };
};

const _InternalDiffView = <T extends unknown>(props: Omit<DiffViewProps<T>, "data" | "registerHighlighter">) => {
  const {
    diffFile,
    className,
    style,
    diffViewMode,
    diffViewWrap,
    diffViewFontSize,
    diffViewHighlight,
    renderWidgetLine,
    renderExtendLine,
    extendData,
    diffViewAddWidget,
    onAddWidgetClick,
  } = props;

  const diffFileId = useMemo(() => diffFile.getId(), [diffFile]);

  const wrapperRef = useRef<HTMLDivElement>();

  // performance optimization
  const useDiffContext = useMemo(
    () => createDiffConfigStore(props, diffFileId),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    []
  );

  useEffect(() => {
    const {
      id,
      setId,
      mode,
      setMode,
      enableAddWidget,
      setEnableAddWidget,
      enableHighlight,
      setEnableHighlight,
      enableWrap,
      setEnableWrap,
      setExtendData,
      fontSize,
      setFontSize,
      onAddWidgetClick: _onAddWidgetClick,
      setOnAddWidgetClick,
      renderExtendLine: _renderExtendLine,
      setRenderExtendLine,
      renderWidgetLine: _renderWidgetLine,
      setRenderWidgetLine,
    } = useDiffContext.getReadonlyState();

    diffFileId && diffFileId !== id && setId(diffFileId);
    diffViewMode && diffViewMode !== mode && setMode(diffViewMode);
    diffViewAddWidget !== enableAddWidget && setEnableAddWidget(diffViewAddWidget);
    diffViewHighlight !== enableHighlight && setEnableHighlight(diffViewHighlight);
    diffViewWrap !== enableWrap && setEnableWrap(diffViewWrap);
    extendData && setExtendData(extendData);
    diffViewFontSize && diffViewFontSize !== fontSize && setFontSize(diffViewFontSize);
    onAddWidgetClick !== _onAddWidgetClick.current && setOnAddWidgetClick({ current: onAddWidgetClick });
    renderExtendLine !== _renderExtendLine && setRenderExtendLine(renderExtendLine);
    renderWidgetLine !== _renderWidgetLine && setRenderWidgetLine(renderWidgetLine);
  }, [
    useDiffContext,
    diffViewFontSize,
    diffViewHighlight,
    diffViewMode,
    diffViewWrap,
    diffViewAddWidget,
    diffFileId,
    renderWidgetLine,
    renderExtendLine,
    extendData,
    onAddWidgetClick,
  ]);

  useEffect(() => {
    const cb = diffFile.subscribe(() => {
      wrapperRef.current?.setAttribute("data-theme", diffFile._getTheme() || "light");
      wrapperRef.current?.setAttribute("data-highlighter", diffFile._getHighlighterName());
    });

    return cb;
  }, [diffFile]);

  const value = useMemo(() => ({ useDiffContext }), [useDiffContext]);

  return (
    <DiffViewContext.Provider value={value}>
      <div
        className="diff-tailwindcss-wrapper"
        data-component="git-diff-view"
        data-theme={diffFile._getTheme() || "light"}
        data-version={__VERSION__}
        data-highlighter={diffFile._getHighlighterName()}
        ref={wrapperRef}
      >
        <div
          className="diff-style-root"
          style={{
            // @ts-ignore
            [diffFontSizeName]: diffViewFontSize + "px",
          }}
        >
          <div
            id={`diff-root${diffFileId}`}
            className={"diff-view-wrapper" + (className ? ` ${className}` : "")}
            style={style}
          >
            {diffViewMode & DiffModeEnum.Split ? (
              <DiffSplitView diffFile={diffFile} />
            ) : (
              <DiffUnifiedView diffFile={diffFile} />
            )}
          </div>
        </div>
      </div>
    </DiffViewContext.Provider>
  );
};

const InternalDiffView = memo(_InternalDiffView);

const DiffViewWithRef = <T extends unknown>(
  props: DiffViewProps<T>,
  ref: ForwardedRef<{ getDiffFileInstance: () => DiffFile }>
) => {
  const { registerHighlighter, data, diffViewTheme, diffFile: _diffFile, ...restProps } = props;

  const diffFile = useMemo(() => {
    if (_diffFile) {
      // missing data for plain file render
      // TODO next release update ?
      // will cause more complex for diffFile flow control, keep current
      const diffFile = DiffFile.createInstance({});
      diffFile._mergeFullBundle(_diffFile._getFullBundle());
      return diffFile;
    } else if (data) {
      return new DiffFile(
        data?.oldFile?.fileName || "",
        data?.oldFile?.content || "",
        data?.newFile?.fileName || "",
        data?.newFile?.content || "",
        data?.hunks || [],
        data?.oldFile?.fileLang || "",
        data?.newFile?.fileLang || ""
      );
    }
    return null;
  }, [data, _diffFile]);

  const diffFileRef = useRef(diffFile);

  if (diffFileRef.current && diffFileRef.current !== diffFile) {
    diffFileRef.current.clear?.();
    diffFileRef.current = diffFile;
  }

  useEffect(() => {
    if (_diffFile && diffFile) {
      _diffFile._addClonedInstance(diffFile);
      return () => {
        _diffFile._delClonedInstance(diffFile);
      };
    }
  }, [diffFile, _diffFile]);

  useEffect(() => {
    if (!diffFile) return;
    diffFile.initTheme(diffViewTheme);
    diffFile.initRaw();
    diffFile.buildSplitDiffLines();
    diffFile.buildUnifiedDiffLines();
  }, [diffFile, diffViewTheme]);

  useEffect(() => {
    if (!diffFile) return;
    if (props.diffViewHighlight) {
      diffFile.initSyntax({ registerHighlighter });
      diffFile.notifyAll();
    }
  }, [diffFile, props.diffViewHighlight, registerHighlighter, diffViewTheme]);

  // fix react strict mode error
  useUnmount(() => (__DEV__ ? diffFile?._destroy?.() : diffFile?.clear?.()), [diffFile]);

  useImperativeHandle(ref, () => ({ getDiffFileInstance: () => diffFile }), [diffFile]);

  if (!diffFile) return null;

  return (
    <InternalDiffView
      key={diffFile.getId()}
      {...restProps}
      diffFile={diffFile}
      diffViewMode={restProps.diffViewMode || DiffModeEnum.SplitGitHub}
      diffViewFontSize={restProps.diffViewFontSize || 14}
    />
  );
};

const InnerDiffView = forwardRef(DiffViewWithRef) as (<T>(
  props: DiffViewProps<T> & { ref?: ForwardedRef<{ getDiffFileInstance: () => DiffFile }> }
) => ReactNode) & { displayName?: string };

export function DiffView<T>(
  props: DiffViewProps_1<T> & { ref?: ForwardedRef<{ getDiffFileInstance: () => DiffFile }> }
): ReactNode;

export function DiffView<T>(
  props: DiffViewProps_2<T> & { ref?: ForwardedRef<{ getDiffFileInstance: () => DiffFile }> }
): ReactNode;

export function DiffView<T>(
  props: DiffViewProps<T> & { ref?: ForwardedRef<{ getDiffFileInstance: () => DiffFile }> }
) {
  return <InnerDiffView {...props} />;
}

DiffView.displayName = "DiffView";

export const version = __VERSION__;

// packages/solid/src/components/DiffView.tsx
/* eslint-disable @typescript-eslint/no-unnecessary-type-constraint */
import { _cacheMap, DiffFile, SplitSide } from "@git-diff-view/core";
import { diffFontSizeName, DiffModeEnum } from "@git-diff-view/utils";
import { type JSXElement, type JSX, createSignal, createEffect, createMemo, onCleanup } from "solid-js";

import { DiffViewContext } from "./DiffViewContext";
import { DiffWidgetContext } from "./DiffWidgetContext";
import { createDiffConfigStore } from "./tools";

import type { DiffHighlighter, DiffHighlighterLang } from "@git-diff-view/core";

_cacheMap.name = "@git-diff-view/solid";

export { SplitSide, DiffModeEnum };

export type DiffViewProps<T> = {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | string | null; content?: string | null };
    hunks: string[];
  };
  extendData?: { oldFile?: Record<string, { data: T } | undefined>; newFile?: Record<string, { data: T } | undefined> };
  initialWidgetState?: { side: SplitSide; lineNumber: number };
  diffFile?: DiffFile;
  class?: string;
  style?: JSX.CSSProperties;
  registerHighlighter?: Omit<DiffHighlighter, "getHighlighterEngine">;
  diffViewMode?: DiffModeEnum;
  diffViewWrap?: boolean;
  diffViewTheme?: "light" | "dark";
  diffViewFontSize?: number;
  diffViewHighlight?: boolean;
  diffViewAddWidget?: boolean;
  renderWidgetLine?: ({
    diffFile,
    side,
    lineNumber,
    onClose,
  }: {
    lineNumber: number;
    side: SplitSide;
    diffFile: DiffFile;
    onClose: () => void;
  }) => JSXElement;
  renderExtendLine?: ({
    diffFile,
    side,
    data,
    lineNumber,
    onUpdate,
  }: {
    lineNumber: number;
    side: SplitSide;
    data: T;
    diffFile: DiffFile;
    onUpdate: () => void;
  }) => JSXElement;
  onAddWidgetClick?: (lineNumber: number, side: SplitSide) => void;
};

type DiffViewProps_1<T> = Omit<DiffViewProps<T>, "data"> & {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | null; content?: string | null };
    hunks: string[];
  };
};

type DiffViewProps_2<T> = Omit<DiffViewProps<T>, "data"> & {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    hunks: string[];
  };
};

const InternalDiffView = <T extends unknown>(props: DiffViewProps<T>) => {
  const getInstance = () => {
    let diffFile: DiffFile | null = null;
    if (props.diffFile) {
      diffFile = DiffFile.createInstance({});
      diffFile._mergeFullBundle(props.diffFile._getFullBundle());
    } else if (props.data) {
      diffFile = new DiffFile(
        props.data.oldFile?.fileName || "",
        props.data.oldFile?.content || "",
        props.data.newFile?.fileName || "",
        props.data.newFile?.content || "",
        props.data.hunks || [],
        props.data.oldFile?.fileLang || "",
        props.data.newFile?.fileLang || ""
      );
    }

    onCleanup(() => diffFile?.clear?.());

    return diffFile;
  };

  let wrapperRef: HTMLDivElement | undefined;

  const diffFile = createMemo(getInstance);

  const [isMounted, setIsMounted] = createSignal(false);

  createEffect(() => {
    setIsMounted(true);
  });

  const [widgetState, setWidgetState] = createSignal<{ side?: SplitSide; lineNumber?: number }>({
    side: props.initialWidgetState?.side,
    lineNumber: props.initialWidgetState?.lineNumber,
  });

  const reactiveHook = createDiffConfigStore(props, diffFile()?.getId() || "");

  createEffect(() => {
    const {
      setId,
      setEnableAddWidget,
      setEnableHighlight,
      setEnableWrap,
      setExtendData,
      setFontSize,
      setIsIsMounted,
      setMode,
      setOnAddWidgetClick,
      setRenderExtendLine,
      setRenderWidgetLine,
    } = reactiveHook.getReadonlyState();
    const currentDiffFile = diffFile();

    setId(currentDiffFile?.getId() || "");

    setEnableAddWidget(!!props.diffViewAddWidget);

    setEnableHighlight(!!props.diffViewHighlight);

    setEnableWrap(!!props.diffViewWrap);

    setFontSize(props.diffViewFontSize || 14);

    setIsIsMounted(isMounted());

    setMode(props.diffViewMode || DiffModeEnum.Split);

    setOnAddWidgetClick({ current: props.onAddWidgetClick });

    setRenderExtendLine(props.renderExtendLine);

    setRenderWidgetLine(props.renderWidgetLine);

    setExtendData(props.extendData);
  });

  createEffect(() => {
    if (props.initialWidgetState) {
      setWidgetState({
        side: props.initialWidgetState.side,
        lineNumber: props.initialWidgetState.lineNumber,
      });
    }
  });

  const initSubscribe = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && props.diffFile && currentDiffFile) {
      props.diffFile._addClonedInstance(currentDiffFile);
      onCleanup(() => props.diffFile?._delClonedInstance(currentDiffFile));
    }
  };

  const initDiff = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && currentDiffFile) {
      currentDiffFile.initTheme(props.diffViewTheme);
      currentDiffFile.initRaw();
      currentDiffFile.buildSplitDiffLines();
      currentDiffFile.buildUnifiedDiffLines();
    }
  };

  const initSyntax = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && currentDiffFile && props.diffViewHighlight) {
      currentDiffFile.initSyntax({ registerHighlighter: props.registerHighlighter });
      currentDiffFile.notifyAll();
    }
  };

  const initAttribute = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && currentDiffFile && wrapperRef) {
      const cb = currentDiffFile.subscribe(() => {
        wrapperRef?.setAttribute("data-theme", currentDiffFile._getTheme() || "light");
        wrapperRef?.setAttribute("data-highlighter", currentDiffFile._getHighlighterName());
      });

      onCleanup(() => cb());
    }
  };

  createEffect(initSubscribe);

  createEffect(initDiff);

  createEffect(initSyntax);

  createEffect(initAttribute);

  onCleanup(() => reactiveHook.clear());

  return (
    <div
      class="diff-tailwindcss-wrapper"
      data-component="git-diff-view"
      data-theme={diffFile()?._getTheme?.() || "light"}
      data-version={__VERSION__}
      data-highlighter={diffFile()?._getHighlighterName?.()}
      ref={wrapperRef}
    >
      <DiffViewContext.Provider value={reactiveHook}>
        <DiffWidgetContext.Provider value={[widgetState, setWidgetState]}>
          <div class="diff-style-root" style={{ [diffFontSizeName]: (props.diffViewFontSize || 14) + "px" }}>
            <div
              id={isMounted() ? `diff-root${diffFile()?.getId()}` : undefined}
              class={"diff-view-wrapper" + (props.class ? ` ${props.class}` : "")}
              style={props.style}
            >
              {/* {!props.diffViewMode || props.diffViewMode & DiffModeEnum.Split ? (
            <DiffSplitView key={DiffModeEnum.Split} diffFile={diffFile.value as DiffFile} />
          ) : (
            <DiffUnifiedView key={DiffModeEnum.Unified} diffFile={diffFile.value as DiffFile} />
          )} */}
            </div>
          </div>
        </DiffWidgetContext.Provider>
      </DiffViewContext.Provider>
    </div>
  );
};

function SolidDiffView<T>(props: DiffViewProps_1<T>): JSXElement;
function SolidDiffView<T>(props: DiffViewProps_2<T>): JSXElement;
function SolidDiffView<T>(props: DiffViewProps<T>): JSXElement {
  return <InternalDiffView {...props} />;
}

export const DiffView = SolidDiffView;
