// packages/svelte/src/lib/components/DiffView.svelte
<script lang="ts" generics="T extends any">
	import { diffFontSizeName, DiffModeEnum } from '@git-diff-view/utils';
	import { DiffFile, type DiffHighlighter, SplitSide } from '@git-diff-view/core';
	import type { Snippet } from 'svelte';
	import { useIsMounted } from '$lib/hooks/useIsMounted.svelte.js';
	import type { HTMLAttributes } from 'svelte/elements';
	import { setFontSize } from '$lib/context/fontSize.js';
	import { setEnableWrap } from '$lib/context/enableWrap.js';
	import { setRenderWidget } from '$lib/context/renderWidget.js';
	import { setId } from '$lib/context/id.js';
	import { setExtend } from '$lib/context/extend.js';
	import { setRenderExtend } from '$lib/context/renderExtend.js';
	import { setOnAddWidgetClick } from '$lib/context/onAddWidgetClick.js';
	import { setEnableHighlight } from '$lib/context/enableHighlight.js';
	import { setEnableAddWidget } from '$lib/context/enableAddWidget.js';
	import { setMode } from '$lib/context/mode.js';

	import DiffSplitView from './DiffSplitView.svelte';
	import DiffUnifiedView from './DiffUnifiedView.svelte';

	interface Props {
		data?: {
			oldFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
			newFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
			hunks: string[];
		};
		extendData?: { oldFile?: Record<string, { data: T }>; newFile?: Record<string, { data: T }> };
		initialWidgetState?: { side: SplitSide; lineNumber: number };
		diffFile?: DiffFile;
		class?: string;
		style?: HTMLAttributes<HTMLDivElement>['style'];
		registerHighlighter?: Omit<DiffHighlighter, 'getHighlighterEngine'>;
		diffViewMode?: DiffModeEnum;
		diffViewWrap?: boolean;
		diffViewTheme?: 'light' | 'dark';
		diffViewFontSize?: number;
		diffViewHighlight?: boolean;
		diffViewAddWidget?: boolean;
		renderWidgetLine?: Snippet<
			[
				{
					lineNumber: number;
					side: SplitSide;
					diffFile: DiffFile;
					onClose: () => void;
				}
			]
		>;
		renderExtendLine?: Snippet<
			[
				{
					lineNumber: number;
					side: SplitSide;
					data: T;
					diffFile: DiffFile;
					onUpdate: () => void;
				}
			]
		>;
		onAddWidgetClick?: (lineNumber: number, side: SplitSide) => void;
	}

	let props: Props = $props();

	let lastDiffFile: { current: DiffFile | null } = { current: null };

	const getInstance = () => {
		lastDiffFile.current?.clear?.();
		if (props.diffFile) {
			const diffFile = DiffFile.createInstance({});

			diffFile._mergeFullBundle(props.diffFile._getFullBundle());

			lastDiffFile.current = diffFile;

			return diffFile;
		} else if (props.data) {
			const data = props.data;

			const diffFile = new DiffFile(
				data.oldFile?.fileName || '',
				data.oldFile?.content || '',
				data.newFile?.fileName || '',
				data.newFile?.content || '',
				data.hunks || [],
				data.oldFile?.fileLang || '',
				data.newFile?.fileLang || ''
			);

			lastDiffFile.current = diffFile;

			return diffFile;
		}
		return null;
	};

	const diffFile = $derived.by(getInstance);

	const getId = () => diffFile?.getId?.();

	const id = $derived.by(getId);

	const widgetState = $state<{ side?: SplitSide; lineNumber?: number }>({
		side: props.initialWidgetState?.side,
		lineNumber: props.initialWidgetState?.lineNumber
	});

	let wrapperRef = $state<HTMLElement | null>(null);

	const setWidget = (v: { side?: SplitSide; lineNumber?: number }) => {
		if (props) widgetState.side = v.side;
		widgetState.lineNumber = v.lineNumber;
	};

	const enableHighlight = $derived(props.diffViewHighlight ?? true);

	const theme = $derived(props.diffViewTheme);

	$effect(() => {
		widgetState.side = props.initialWidgetState?.side;
		widgetState.lineNumber = props.initialWidgetState?.lineNumber;
	});

	$effect(() => {
		if (props.data || props.diffFile) {
			widgetState.side = undefined;
			widgetState.lineNumber = undefined;
		}
	});

	const unSubscribe = { current: () => {} };

	const isMounted = $derived.by(useIsMounted());

	const initSubscribe = () => {
		unSubscribe?.current?.();
		if (!isMounted || !diffFile || !props.diffFile) return;
		props.diffFile._addClonedInstance(diffFile);
		unSubscribe.current = () => props.diffFile?._delClonedInstance(diffFile);
	};

	$effect(initSubscribe);

	const initDiff = () => {
		if (!diffFile || !isMounted) return;
		diffFile.initTheme(theme);
		diffFile.initRaw();
		diffFile.buildSplitDiffLines();
		diffFile.buildUnifiedDiffLines();
	};

	$effect(initDiff);

	const initSyntax = () => {
		if (!diffFile || !isMounted || !enableHighlight) return;
		diffFile.initSyntax({
			registerHighlighter: props.registerHighlighter
		});
		diffFile.notifyAll();
	};

	$effect(initSyntax);

	const unSubscribeAttr = { current: () => {} };

	const initAttribute = () => {
		unSubscribeAttr?.current?.();

		if (!isMounted || !diffFile || !wrapperRef) return;

		theme;

		const init = () => {
			wrapperRef?.setAttribute('data-theme', diffFile._getTheme() || 'light');
			wrapperRef?.setAttribute('data-highlighter', diffFile._getHighlighterName());
		};

		init();

		unSubscribeAttr.current = diffFile.subscribe(init);
	};

	$effect(initAttribute);

	setFontSize(props);

	setEnableWrap(props);

	setRenderWidget(props);

	setRenderExtend(props);

	setOnAddWidgetClick(props);

	setEnableHighlight(props);

	setEnableAddWidget(props);

	setMode(props);

	setExtend<T>(props);

	setId(() => diffFile?.getId() || '');
</script>

{#if diffFile}
	<div
		class="diff-tailwindcss-wrapper"
		data-component="git-diff-view"
		data-theme={diffFile?._getTheme() || 'light'}
		data-highlighter={diffFile?._getHighlighterName()}
		{@attach (e) => (wrapperRef = e)}
	>
		<div class="diff-style-root" style={`${diffFontSizeName}:${props.diffViewFontSize || 14}px`}>
			<div
				id={isMounted ? `diff-root${id}` : undefined}
				class={`diff-view-wrapper` + (props.class ? ` ${props.class}` : '')}
				style={props.style}
			>
				{#if !props.diffViewMode || props.diffViewMode & DiffModeEnum.Split}
					<DiffSplitView {diffFile} />
				{:else}
					<DiffUnifiedView {diffFile} />
				{/if}
			</div>
		</div>
	</div>
{/if}

// packages/solid/src/components/DiffView.tsx
/* eslint-disable @typescript-eslint/no-unnecessary-type-constraint */
import { _cacheMap, DiffFile, SplitSide } from "@git-diff-view/core";
import { diffFontSizeName, DiffModeEnum } from "@git-diff-view/utils";
import { type JSXElement, type JSX, createSignal, createEffect, createMemo, onCleanup } from "solid-js";

import { DiffViewContext } from "./DiffViewContext";
import { DiffWidgetContext } from "./DiffWidgetContext";
import { createDiffConfigStore } from "./tools";

import type { DiffHighlighter, DiffHighlighterLang } from "@git-diff-view/core";

_cacheMap.name = "@git-diff-view/solid";

export { SplitSide, DiffModeEnum };

export type DiffViewProps<T> = {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | string | null; content?: string | null };
    hunks: string[];
  };
  extendData?: { oldFile?: Record<string, { data: T } | undefined>; newFile?: Record<string, { data: T } | undefined> };
  initialWidgetState?: { side: SplitSide; lineNumber: number };
  diffFile?: DiffFile;
  class?: string;
  style?: JSX.CSSProperties;
  registerHighlighter?: Omit<DiffHighlighter, "getHighlighterEngine">;
  diffViewMode?: DiffModeEnum;
  diffViewWrap?: boolean;
  diffViewTheme?: "light" | "dark";
  diffViewFontSize?: number;
  diffViewHighlight?: boolean;
  diffViewAddWidget?: boolean;
  renderWidgetLine?: ({
    diffFile,
    side,
    lineNumber,
    onClose,
  }: {
    lineNumber: number;
    side: SplitSide;
    diffFile: DiffFile;
    onClose: () => void;
  }) => JSXElement;
  renderExtendLine?: ({
    diffFile,
    side,
    data,
    lineNumber,
    onUpdate,
  }: {
    lineNumber: number;
    side: SplitSide;
    data: T;
    diffFile: DiffFile;
    onUpdate: () => void;
  }) => JSXElement;
  onAddWidgetClick?: (lineNumber: number, side: SplitSide) => void;
};

type DiffViewProps_1<T> = Omit<DiffViewProps<T>, "data"> & {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | null; content?: string | null };
    hunks: string[];
  };
};

type DiffViewProps_2<T> = Omit<DiffViewProps<T>, "data"> & {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    hunks: string[];
  };
};

const InternalDiffView = <T extends unknown>(props: DiffViewProps<T>) => {
  const getInstance = () => {
    let diffFile: DiffFile | null = null;
    if (props.diffFile) {
      diffFile = DiffFile.createInstance({});
      diffFile._mergeFullBundle(props.diffFile._getFullBundle());
    } else if (props.data) {
      diffFile = new DiffFile(
        props.data.oldFile?.fileName || "",
        props.data.oldFile?.content || "",
        props.data.newFile?.fileName || "",
        props.data.newFile?.content || "",
        props.data.hunks || [],
        props.data.oldFile?.fileLang || "",
        props.data.newFile?.fileLang || ""
      );
    }

    onCleanup(() => diffFile?.clear?.());

    return diffFile;
  };

  let wrapperRef: HTMLDivElement | undefined;

  const diffFile = createMemo(getInstance);

  const [isMounted, setIsMounted] = createSignal(false);

  createEffect(() => {
    setIsMounted(true);
  });

  const [widgetState, setWidgetState] = createSignal<{ side?: SplitSide; lineNumber?: number }>({
    side: props.initialWidgetState?.side,
    lineNumber: props.initialWidgetState?.lineNumber,
  });

  const reactiveHook = createDiffConfigStore(props, diffFile()?.getId() || "");

  createEffect(() => {
    const {
      setId,
      setEnableAddWidget,
      setEnableHighlight,
      setEnableWrap,
      setExtendData,
      setFontSize,
      setIsIsMounted,
      setMode,
      setOnAddWidgetClick,
      setRenderExtendLine,
      setRenderWidgetLine,
    } = reactiveHook.getReadonlyState();
    const currentDiffFile = diffFile();

    setId(currentDiffFile?.getId() || "");

    setEnableAddWidget(!!props.diffViewAddWidget);

    setEnableHighlight(!!props.diffViewHighlight);

    setEnableWrap(!!props.diffViewWrap);

    setFontSize(props.diffViewFontSize || 14);

    setIsIsMounted(isMounted());

    setMode(props.diffViewMode || DiffModeEnum.Split);

    setOnAddWidgetClick({ current: props.onAddWidgetClick });

    setRenderExtendLine(props.renderExtendLine);

    setRenderWidgetLine(props.renderWidgetLine);

    setExtendData(props.extendData);
  });

  createEffect(() => {
    if (props.initialWidgetState) {
      setWidgetState({
        side: props.initialWidgetState.side,
        lineNumber: props.initialWidgetState.lineNumber,
      });
    }
  });

  const initSubscribe = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && props.diffFile && currentDiffFile) {
      props.diffFile._addClonedInstance(currentDiffFile);
      onCleanup(() => props.diffFile?._delClonedInstance(currentDiffFile));
    }
  };

  const initDiff = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && currentDiffFile) {
      currentDiffFile.initTheme(props.diffViewTheme);
      currentDiffFile.initRaw();
      currentDiffFile.buildSplitDiffLines();
      currentDiffFile.buildUnifiedDiffLines();
    }
  };

  const initSyntax = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && currentDiffFile && props.diffViewHighlight) {
      currentDiffFile.initSyntax({ registerHighlighter: props.registerHighlighter });
      currentDiffFile.notifyAll();
    }
  };

  const initAttribute = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && currentDiffFile && wrapperRef) {
      const cb = currentDiffFile.subscribe(() => {
        wrapperRef?.setAttribute("data-theme", currentDiffFile._getTheme() || "light");
        wrapperRef?.setAttribute("data-highlighter", currentDiffFile._getHighlighterName());
      });

      onCleanup(() => cb());
    }
  };

  createEffect(initSubscribe);

  createEffect(initDiff);

  createEffect(initSyntax);

  createEffect(initAttribute);

  onCleanup(() => reactiveHook.clear());

  return (
    <div
      class="diff-tailwindcss-wrapper"
      data-component="git-diff-view"
      data-theme={diffFile()?._getTheme?.() || "light"}
      data-version={__VERSION__}
      data-highlighter={diffFile()?._getHighlighterName?.()}
      ref={wrapperRef}
    >
      <DiffViewContext.Provider value={reactiveHook}>
        <DiffWidgetContext.Provider value={[widgetState, setWidgetState]}>
          <div class="diff-style-root" style={{ [diffFontSizeName]: (props.diffViewFontSize || 14) + "px" }}>
            <div
              id={isMounted() ? `diff-root${diffFile()?.getId()}` : undefined}
              class={"diff-view-wrapper" + (props.class ? ` ${props.class}` : "")}
              style={props.style}
            >
              {/* {!props.diffViewMode || props.diffViewMode & DiffModeEnum.Split ? (
            <DiffSplitView key={DiffModeEnum.Split} diffFile={diffFile.value as DiffFile} />
          ) : (
            <DiffUnifiedView key={DiffModeEnum.Unified} diffFile={diffFile.value as DiffFile} />
          )} */}
            </div>
          </div>
        </DiffWidgetContext.Provider>
      </DiffViewContext.Provider>
    </div>
  );
};

function SolidDiffView<T>(props: DiffViewProps_1<T>): JSXElement;
function SolidDiffView<T>(props: DiffViewProps_2<T>): JSXElement;
function SolidDiffView<T>(props: DiffViewProps<T>): JSXElement {
  return <InternalDiffView {...props} />;
}

export const DiffView = SolidDiffView;
