// packages/vue/src/components/DiffUnifiedExtendLine.tsx
import { computed, defineComponent, ref } from "vue";

import { SplitSide } from "..";
import { useExtendData, useSlots } from "../context";
import { useDomWidth } from "../hooks/useDomWidth";

import type { DiffFile } from "@git-diff-view/core";

export const DiffUnifiedExtendLine = defineComponent(
  (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
    const extendData = useExtendData();

    const slots = useSlots();

    const unifiedItem = computed(() => props.diffFile.getUnifiedLine(props.index));

    const oldExtend = computed(() => extendData.value?.oldFile?.[unifiedItem.value.oldLineNumber]);

    const newExtend = computed(() => extendData.value?.newFile?.[unifiedItem.value.newLineNumber]);

    const currentIsHidden = computed(() => unifiedItem.value.isHidden);

    const currentIsShow = computed(() =>
      Boolean((oldExtend.value || newExtend.value) && !currentIsHidden.value && slots.extend)
    );

    const width = useDomWidth({
      selector: ref(".unified-diff-table-wrapper"),
      enable: currentIsShow,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr data-line={`${props.lineNumber}-extend`} data-state="extend" class="diff-line diff-line-extend">
          <td class="diff-line-extend-content p-0 align-top" colspan={2}>
            <div class="diff-line-extend-wrapper sticky left-0 z-[1]" style={{ width: width.value + "px" }}>
              {width.value > 0 &&
                oldExtend.value &&
                slots.extend({
                  diffFile: props.diffFile,
                  side: SplitSide.old,
                  lineNumber: unifiedItem.value.oldLineNumber,
                  data: oldExtend.value.data,
                  onUpdate: props.diffFile.notifyAll,
                })}
              {width.value > 0 &&
                newExtend.value &&
                slots.extend({
                  diffFile: props.diffFile,
                  side: SplitSide.new,
                  lineNumber: unifiedItem.value.newLineNumber,
                  data: newExtend.value.data,
                  onUpdate: props.diffFile.notifyAll,
                })}
            </div>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffUnifiedExtendLine", props: ["diffFile", "index", "lineNumber"] }
);

// packages/solid/src/components/DiffUnifiedExtendLine.tsx
import { SplitSide, type DiffFile } from "@git-diff-view/core";
import { createMemo, Show } from "solid-js";

import { useDomWidth, useExtendData, useRenderExtend } from "../hooks";

export const DiffUnifiedExtendLine = (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
  const extendData = useExtendData();

  const renderExtend = useRenderExtend();

  const unifiedItem = createMemo(() => props.diffFile.getUnifiedLine(props.index));

  const oldExtend = createMemo(() => extendData()?.oldFile?.[unifiedItem()?.oldLineNumber || 0]);

  const newExtend = createMemo(() => extendData()?.newFile?.[unifiedItem()?.newLineNumber || 0]);

  const currentIsHidden = createMemo(() => unifiedItem()?.isHidden);

  const currentIsShow = createMemo(() => Boolean((oldExtend() || newExtend()) && !currentIsHidden() && renderExtend()));

  const lineSelector = createMemo(() => `.unified-diff-table-wrapper`);

  const width = useDomWidth({
    selector: lineSelector,
    enable: currentIsShow,
  });

  return (
    <Show when={currentIsShow()}>
      <tr data-line={`${props.lineNumber}-extend`} data-state="extend" class="diff-line diff-line-extend">
        <td class="diff-line-extend-content p-0 align-top" colspan={2}>
          <div class="diff-line-extend-wrapper sticky left-0 z-[1]" style={{ width: width() + "px" }}>
            {width() > 0 &&
              oldExtend() &&
              renderExtend()?.({
                diffFile: props.diffFile,
                side: SplitSide.old,
                lineNumber: unifiedItem()?.oldLineNumber || 0,
                data: oldExtend()?.data,
                onUpdate: props.diffFile.notifyAll,
              })}
            {width() > 0 &&
              newExtend() &&
              renderExtend()?.({
                diffFile: props.diffFile,
                side: SplitSide.new,
                lineNumber: unifiedItem().newLineNumber || 0,
                data: newExtend()?.data,
                onUpdate: props.diffFile.notifyAll,
              })}
          </div>
        </td>
      </tr>
    </Show>
  );
};
