// packages/vue/src/components/DiffUnifiedLine.tsx
import { defineComponent, ref } from "vue";

import { SplitSide } from "..";
import { useEnableAddWidget, useEnableHighlight, useEnableWrap, useOnAddWidgetClick } from "../context";
import { useSubscribeDiffFile } from "../hooks/useSubscribeDiffFile";

import {
  addContentBGName,
  addLineNumberBGName,
  delContentBGName,
  delLineNumberBGName,
  expandContentBGName,
  plainContentBGName,
  plainLineNumberBGName,
  plainLineNumberColorName,
} from "./color";
import { DiffUnifiedAddWidget } from "./DiffAddWidget";
import { DiffContent } from "./DiffContent";

import type { DiffFileExtends } from "../utils";
import type { DiffFile, SyntaxLine, DiffLine } from "@git-diff-view/core";

const DiffUnifiedOldLine = ({
  index,
  diffLine,
  rawLine,
  syntaxLine,
  lineNumber,
  diffFile,
  enableWrap,
  enableHighlight,
  onAddWidgetClick,
}: {
  index: number;
  lineNumber: number;
  rawLine: string;
  syntaxLine?: SyntaxLine;
  diffLine?: DiffLine;
  diffFile: DiffFile;
  enableWrap: boolean;
  enableHighlight: boolean;
  onAddWidgetClick?: (event: "onAddWidgetClick", lineNumber: number, side: SplitSide) => void;
}) => {
  return (
    <tr data-line={index} data-state="diff" data-mode="del" class="diff-line group" style={{ backgroundColor: `var(${delContentBGName})` }}>
      <td
        class="diff-line-num left-0 pl-[10px] pr-[10px] text-left select-none w-[1%] min-w-[60px] whitespace-nowrap align-top"
        style={{
          position: enableWrap ? "relative" : "sticky",
          color: `var(${plainLineNumberColorName})`,
          backgroundColor: `var(${delLineNumberBGName})`,
        }}
      >
        <DiffUnifiedAddWidget
          index={index - 1}
          lineNumber={lineNumber}
          diffFile={diffFile as DiffFileExtends}
          side={SplitSide.old}
          onWidgetClick={onAddWidgetClick}
        />
        <div class="flex">
          <span data-line-num-old={lineNumber} class="inline-block w-[50%]">
            {lineNumber}
          </span>
          <span class="w-[10px] shrink-0" />
          <span class="inline-block w-[50%]" />
        </div>
      </td>
      <td class="diff-line-content pr-[10px] align-top">
        <DiffContent
          enableWrap={enableWrap}
          diffFile={diffFile}
          enableHighlight={enableHighlight}
          rawLine={rawLine}
          diffLine={diffLine}
          syntaxLine={syntaxLine}
        />
      </td>
    </tr>
  );
};

const DiffUnifiedNewLine = ({
  index,
  diffLine,
  rawLine,
  syntaxLine,
  lineNumber,
  diffFile,
  enableWrap,
  enableHighlight,
  onAddWidgetClick,
}: {
  index: number;
  lineNumber: number;
  rawLine: string;
  syntaxLine?: SyntaxLine;
  diffLine?: DiffLine;
  diffFile: DiffFile;
  enableWrap: boolean;
  enableHighlight: boolean;
  onAddWidgetClick?: (event: "onAddWidgetClick", lineNumber: number, side: SplitSide) => void;
}) => {
  return (
    <tr data-line={index} data-state="diff" data-mode="add" class="diff-line group" style={{ backgroundColor: `var(${addContentBGName})` }}>
      <td
        class="diff-line-num left-0 pl-[10px] pr-[10px] text-left select-none w-[1%] min-w-[60px] whitespace-nowrap align-top"
        style={{
          position: enableWrap ? "relative" : "sticky",
          color: `var(${plainLineNumberColorName})`,
          backgroundColor: `var(${addLineNumberBGName})`,
        }}
      >
        <DiffUnifiedAddWidget
          index={index - 1}
          lineNumber={lineNumber}
          diffFile={diffFile as DiffFileExtends}
          side={SplitSide.new}
          onWidgetClick={onAddWidgetClick}
        />
        <div class="flex">
          <span class="inline-block w-[50%]" />
          <span class="shrink-0 w-[10px]" />
          <span data-line-num-new={lineNumber} class="inline-block w-[50%]">
            {lineNumber}
          </span>
        </div>
      </td>
      <td class="diff-line-content pr-[10px] align-top">
        <DiffContent
          enableWrap={enableWrap}
          diffFile={diffFile}
          enableHighlight={enableHighlight}
          rawLine={rawLine}
          diffLine={diffLine}
          syntaxLine={syntaxLine}
        />
      </td>
    </tr>
  );
};

export const DiffUnifiedLine = defineComponent(
  (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
    const unifiedItem = ref(props.diffFile.getUnifiedLine(props.index));

    const enableWrap = useEnableWrap();

    const onAddWidgetClick = useOnAddWidgetClick();

    const enableHighlight = useEnableHighlight();

    const enableAddWidget = useEnableAddWidget();

    const currentItemHasHidden = ref(unifiedItem.value?.isHidden);

    const currentItemHasChange = ref(unifiedItem.value?.diff?.isIncludeableLine());

    const currentSyntaxItem = ref(
      unifiedItem.value?.newLineNumber
        ? props.diffFile.getNewSyntaxLine(unifiedItem.value.newLineNumber)
        : unifiedItem.value?.oldLineNumber
          ? props.diffFile.getOldSyntaxLine(unifiedItem.value.oldLineNumber)
          : undefined
    );

    useSubscribeDiffFile(props, (diffFile) => (unifiedItem.value = diffFile.getUnifiedLine(props.index)));

    useSubscribeDiffFile(props, () => (currentItemHasHidden.value = unifiedItem.value?.isHidden));

    useSubscribeDiffFile(props, () => (currentItemHasChange.value = unifiedItem.value?.diff?.isIncludeableLine()));

    useSubscribeDiffFile(
      props,
      (diffFile) =>
        (currentSyntaxItem.value = unifiedItem.value?.newLineNumber
          ? diffFile.getNewSyntaxLine(unifiedItem.value.newLineNumber)
          : unifiedItem.value?.oldLineNumber
            ? diffFile.getOldSyntaxLine(unifiedItem.value.oldLineNumber)
            : undefined)
    );

    return () => {
      if (currentItemHasHidden.value) return null;

      if (currentItemHasChange.value) {
        if (unifiedItem.value.oldLineNumber) {
          return (
            <DiffUnifiedOldLine
              index={props.lineNumber}
              enableWrap={enableWrap.value}
              diffFile={props.diffFile}
              rawLine={unifiedItem.value.value || ""}
              diffLine={unifiedItem.value.diff}
              syntaxLine={currentSyntaxItem.value}
              enableHighlight={enableHighlight.value}
              lineNumber={unifiedItem.value.oldLineNumber}
              onAddWidgetClick={onAddWidgetClick}
            />
          );
        } else {
          return (
            <DiffUnifiedNewLine
              index={props.lineNumber}
              enableWrap={enableWrap.value}
              diffFile={props.diffFile}
              rawLine={unifiedItem.value.value || ""}
              diffLine={unifiedItem.value.diff}
              syntaxLine={currentSyntaxItem.value}
              enableHighlight={enableHighlight.value}
              lineNumber={unifiedItem.value.newLineNumber!}
              onAddWidgetClick={onAddWidgetClick}
            />
          );
        }
      } else {
        return (
          <tr
            data-line={props.lineNumber}
            data-state={unifiedItem.value.diff ? "diff" : "plain"}
            class="diff-line group"
            style={{
              backgroundColor: unifiedItem.value.diff ? `var(${plainContentBGName})` : `var(${expandContentBGName})`,
            }}
          >
            <td
              class="diff-line-num left-0 pl-[10px] pr-[10px] text-left select-none w-[1%] min-w-[60px] whitespace-nowrap align-top"
              style={{
                position: enableWrap.value ? "relative" : "sticky",
                color: `var(${plainLineNumberColorName})`,
                backgroundColor: unifiedItem.value.diff ? `var(${plainLineNumberBGName})` : `var(${expandContentBGName})`,
              }}
            >
              {enableAddWidget.value && unifiedItem.value.diff && (
                <DiffUnifiedAddWidget
                  index={props.index}
                  diffFile={props.diffFile as DiffFileExtends}
                  lineNumber={unifiedItem.value.newLineNumber}
                  side={SplitSide.new}
                  onWidgetClick={onAddWidgetClick}
                />
              )}
              <div class="flex opacity-[0.5]">
                <span data-line-num-old={unifiedItem.value.oldLineNumber} class="inline-block w-[50%]">
                  {unifiedItem.value.oldLineNumber}
                </span>
                <span class="w-[10px] shrink-0" />
                <span data-line-num-new={unifiedItem.value.newLineNumber} class="inline-block w-[50%]">
                  {unifiedItem.value.newLineNumber}
                </span>
              </div>
            </td>
            <td class="diff-line-content pr-[10px] align-top">
              <DiffContent
                enableWrap={enableWrap.value}
                diffFile={props.diffFile}
                enableHighlight={enableHighlight.value}
                rawLine={unifiedItem.value.value || ""}
                diffLine={unifiedItem.value.diff}
                syntaxLine={currentSyntaxItem.value}
              />
            </td>
          </tr>
        );
      }
    };
  },
  { name: "DiffUnifiedLine", props: ["diffFile", "index", "lineNumber"] }
);

// src/components/DiffUnifiedLine.tsx
import { DiffFile, DiffFileExtends, SyntaxLine } from "../diff";
import { DiffLine } from "../diff/diff-line";
import { DiffUnifiedAddWidget } from "./DiffAddWidget";
import { DiffContent } from "./DiffContent";
import {
  addContentBGName,
  addLineNumberBGName,
  delContentBGName,
  delLineNumberBGName,
  expandContentBGName,
  plainContentBGName,
  plainLineNumberBGName,
  plainLineNumberColorName,
} from "./color";

const DiffUnifiedOldLine = ({
  index,
  diffLine,
  rawLine,
  syntaxLine,
  lineNumber,
  diffFile,
  isWrap,
  isHighlight,
}: {
  index: number;
  lineNumber: number;
  rawLine: string;
  syntaxLine?: SyntaxLine;
  diffLine?: DiffLine;
  diffFile: DiffFile;
  isWrap: boolean;
  isHighlight: boolean;
}) => {
  return (
    <tr
      data-line={index}
      data-state="diff"
      data-mode="del"
      className="diff-line group"
      style={{ backgroundColor: `var(${delContentBGName})` }}
    >
      <td
        className="diff-line-num left-[0] pl-[10px] pr-[10px] text-left select-none w-[1%] min-w-[60px] whitespace-nowrap align-top"
        style={{
          position: isWrap ? "relative" : "sticky",
          color: `var(${plainLineNumberColorName})`,
          backgroundColor: `var(${delLineNumberBGName})`,
        }}
      >
        <DiffUnifiedAddWidget
          index={index - 1}
          diffFile={diffFile as DiffFileExtends}
        />
        <div className="flex">
          <span data-line-num-old={lineNumber} className="inline-block w-[50%]">
            {lineNumber}
          </span>
          <span className="w-[10px] shrink-0" />
          <span className="inline-block w-[50%]" />
        </div>
      </td>
      <td className="diff-line-content pr-[10px] align-top">
        <DiffContent
          isWrap={isWrap}
          diffFile={diffFile}
          isHighlight={isHighlight}
          rawLine={rawLine}
          diffLine={diffLine}
          syntaxLine={syntaxLine}
        />
      </td>
    </tr>
  );
};

const DiffUnifiedNewLine = ({
  index,
  diffLine,
  rawLine,
  syntaxLine,
  lineNumber,
  diffFile,
  isWrap,
  isHighlight,
}: {
  index: number;
  lineNumber: number;
  rawLine: string;
  syntaxLine?: SyntaxLine;
  diffLine?: DiffLine;
  diffFile: DiffFile;
  isWrap: boolean;
  isHighlight: boolean;
}) => {
  return (
    <tr
      data-line={index}
      data-state="diff"
      data-mode="add"
      className="diff-line group"
      style={{ backgroundColor: `var(${addContentBGName})` }}
    >
      <td
        className="diff-line-num left-[0] pl-[10px] pr-[10px] text-left select-none w-[1%] min-w-[60px] whitespace-nowrap align-top"
        style={{
          position: isWrap ? "relative" : "sticky",
          color: `var(${plainLineNumberColorName})`,
          backgroundColor: `var(${addLineNumberBGName})`,
        }}
      >
        <DiffUnifiedAddWidget
          index={index - 1}
          diffFile={diffFile as DiffFileExtends}
        />
        <div className="flex">
          <span className="inline-block w-[50%]" />
          <span className="shrink-0 w-[10px]" />
          <span data-line-num-new={lineNumber} className="inline-block w-[50%]">
            {lineNumber}
          </span>
        </div>
      </td>
      <td className="diff-line-content pr-[10px] align-top">
        <DiffContent
          isWrap={isWrap}
          diffFile={diffFile}
          isHighlight={isHighlight}
          rawLine={rawLine}
          diffLine={diffLine}
          syntaxLine={syntaxLine}
        />
      </td>
    </tr>
  );
};

export const DiffUnifiedLine = ({
  index,
  diffFile,
  lineNumber,
  isWrap,
  isHighlight,
}: {
  index: number;
  diffFile: DiffFile;
  lineNumber: number;
  isWrap: boolean;
  isHighlight: boolean;
}) => {
  const unifiedLine = diffFile.getUnifiedLine(index);

  if (unifiedLine?.isHidden) return null;

  const hasDiff = unifiedLine.diff;

  const hasChange = unifiedLine.diff?.isIncludeableLine();

  const rawLine = unifiedLine.value || "";

  const diffLine = unifiedLine.diff;

  const newLineNumber = unifiedLine.newLineNumber;

  const oldLinenumber = unifiedLine.oldLineNumber;

  const syntaxLine = newLineNumber
    ? diffFile.getNewSyntaxLine(newLineNumber)
    : oldLinenumber
    ? diffFile.getOldSyntaxLine(oldLinenumber)
    : undefined;

  if (hasChange) {
    if (unifiedLine.oldLineNumber) {
      return (
        <DiffUnifiedOldLine
          index={lineNumber}
          isWrap={isWrap}
          diffFile={diffFile}
          rawLine={rawLine}
          diffLine={diffLine}
          syntaxLine={syntaxLine}
          isHighlight={isHighlight}
          lineNumber={unifiedLine.oldLineNumber}
        />
      );
    } else {
      return (
        <DiffUnifiedNewLine
          index={lineNumber}
          isWrap={isWrap}
          rawLine={rawLine}
          diffLine={diffLine}
          diffFile={diffFile}
          syntaxLine={syntaxLine}
          isHighlight={isHighlight}
          lineNumber={unifiedLine.newLineNumber!}
        />
      );
    }
  } else {
    return (
      <tr
        data-line={lineNumber}
        data-state={unifiedLine.diff ? "diff" : "plain"}
        className="diff-line group"
        style={{
          backgroundColor: hasDiff
            ? `var(${plainContentBGName})`
            : `var(${expandContentBGName})`,
        }}
      >
        <td
          className="diff-line-num left-[0] pl-[10px] pr-[10px] text-left select-none w-[1%] min-w-[60px] whitespace-nowrap align-top"
          style={{
            position: isWrap ? "relative" : "sticky",
            color: `var(${plainLineNumberColorName})`,
            backgroundColor: hasDiff
              ? `var(${plainLineNumberBGName})`
              : `var(${expandContentBGName})`,
          }}
        >
          {hasDiff && (
            <DiffUnifiedAddWidget
              index={index}
              diffFile={diffFile as DiffFileExtends}
            />
          )}
          <div className="flex opacity-[0.5]">
            <span
              data-line-num-old={unifiedLine.oldLineNumber}
              className="inline-block w-[50%]"
            >
              {unifiedLine.oldLineNumber}
            </span>
            <span className="w-[10px] shrink-0" />
            <span
              data-line-num-new={unifiedLine.newLineNumber}
              className="inline-block w-[50%]"
            >
              {unifiedLine.newLineNumber}
            </span>
          </div>
        </td>
        <td className="diff-line-content pr-[10px] align-top">
          <DiffContent
            isWrap={isWrap}
            diffFile={diffFile}
            isHighlight={isHighlight}
            rawLine={rawLine}
            diffLine={diffLine}
            syntaxLine={syntaxLine}
          />
        </td>
      </tr>
    );
  }
};
