// packages/react/src/components/DiffSplitExtendLine.tsx
import * as React from "react";

import { useDiffViewContext, SplitSide } from "..";
import { useDomWidth } from "../hooks/useDomWidth";
import { useSyncHeight } from "../hooks/useSyncHeight";

import { emptyBGName } from "./color";
import { DiffFile } from "@git-diff-view/core";

const _DiffSplitExtendLine = ({ index, diffFile, side, lineNumber }: { index: number; side: SplitSide; diffFile: DiffFile; lineNumber: number }) => {
  const { extendData, renderExtendLine } = useDiffViewContext();

  const oldItem = diffFile.getSplitLeftLine(index);

  const newItem = diffFile.getSplitRightLine(index);

  const oldExtend = extendData?.oldFile?.[oldItem?.lineNumber];

  const newExtend = extendData?.newFile?.[newItem.lineNumber];

  const currentExtend = side === SplitSide.old ? oldExtend : newExtend;

  const currentLineNumber = side === SplitSide.old ? oldItem.lineNumber : newItem.lineNumber;

  useSyncHeight({
    selector: `tr[data-line="${lineNumber}-extend"]`,
    side: side === SplitSide.old ? "left" : "right",
    enable: !!currentExtend,
  });

  const width = useDomWidth({
    selector: side === SplitSide.old ? ".old-diff-table-wrapper" : ".new-diff-table-wrapper",
    enable: !!currentExtend,
  });

  return (
    <tr
      data-line={`${lineNumber}-extend`}
      data-state="extend"
      data-side={side === SplitSide.old ? "left" : "right"}
      className={"diff-line diff-line-extend" + !currentExtend ? " diff-line-extend-empty" : ""}
      style={{
        backgroundColor: !currentExtend ? `var(${emptyBGName})` : undefined,
      }}
    >
      <td className="diff-line-extend-content align-top p-0" colSpan={2}>
        <div className="diff-line-extend-wrapper sticky left-0" style={{ width }}>
          {width > 0 &&
            currentExtend &&
            renderExtendLine({ diffFile, side, lineNumber: currentLineNumber, data: currentExtend.data, onUpdate: diffFile.notifyAll })}
        </div>
      </td>
    </tr>
  );
};

export const DiffSplitExtendLine = ({ index, diffFile, side, lineNumber }: { index: number; side: SplitSide; diffFile: DiffFile; lineNumber: number }) => {
  const { extendData } = useDiffViewContext();

  const oldItem = diffFile.getSplitLeftLine(index);

  const newItem = diffFile.getSplitRightLine(index);

  const currentItem = side === SplitSide.old ? oldItem : newItem;

  const oldExtend = extendData?.oldFile?.[oldItem?.lineNumber];

  const newExtend = extendData?.newFile?.[newItem.lineNumber];

  const currentIsShow = (oldExtend || newExtend) && currentItem && !currentItem.isHidden && currentItem.diff;

  if (!currentIsShow) return null;

  return <_DiffSplitExtendLine index={index} diffFile={diffFile} side={side} lineNumber={lineNumber} />;
};

// packages/vue/src/components/DiffSplitExtendLine.tsx
import { computed, defineComponent, ref } from "vue";

import { useExtendData, useSlots } from "../context";
import { useDomWidth } from "../hooks/useDomWidth";
import { useSubscribeDiffFile } from "../hooks/useSubscribeDiffFile";
import { useSyncHeight } from "../hooks/useSyncHeight";

import { emptyBGName } from "./color";
import { SplitSide } from "./DiffView";

import type { DiffFile } from "@git-diff-view/core";

export const DiffSplitExtendLine = defineComponent(
  (props: { index: number; side: SplitSide; diffFile: DiffFile; lineNumber: number }) => {
    const extendData = useExtendData();

    const slots = useSlots();

    const side = computed(() => (props.side === SplitSide.old ? "left" : "right"));

    const lineSelector = computed(() => `tr[data-line="${props.lineNumber}-extend"]`);

    const wrapperSelector = computed(() => (props.side === SplitSide.old ? ".old-diff-table-wrapper" : ".new-diff-table-wrapper"));

    const oldItem = ref(props.diffFile.getSplitLeftLine(props.index));

    const newItem = ref(props.diffFile.getSplitRightLine(props.index));

    const currentItem = computed(() => (props.side === SplitSide.old ? oldItem.value : newItem.value));

    const oldExtend = ref(extendData.value?.oldFile?.[oldItem.value?.lineNumber]);

    const newExtend = ref(extendData.value?.newFile?.[newItem.value.lineNumber]);

    useSubscribeDiffFile(props, (diffFile) => (oldItem.value = diffFile.getSplitLeftLine(props.index)));

    useSubscribeDiffFile(props, (diffFile) => (newItem.value = diffFile.getSplitRightLine(props.index)));

    useSubscribeDiffFile(props, () => (oldExtend.value = extendData.value?.oldFile?.[oldItem.value?.lineNumber]));

    useSubscribeDiffFile(props, () => (newExtend.value = extendData.value?.newFile?.[newItem.value?.lineNumber]));

    const currentExtend = computed(() => (props.side === SplitSide.old ? oldExtend.value : newExtend.value));

    const currentEnable = computed(() => (props.side === SplitSide.old ? !!oldExtend.value : !!newExtend.value));

    const currentLineNumber = computed(() => (props.side === SplitSide.old ? oldItem.value.lineNumber : newItem.value.lineNumber));

    const currentIsShow = computed(() =>
      Boolean((oldExtend.value || newExtend.value) && currentItem.value && !currentItem.value.isHidden && currentItem.value.diff)
    );

    useSyncHeight({
      selector: lineSelector,
      side: side,
      enable: currentEnable,
    });

    const width = useDomWidth({
      selector: wrapperSelector,
      enable: currentEnable,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr
          data-line={`${props.lineNumber}-extend`}
          data-state="extend"
          data-side={props.side === SplitSide.old ? "left" : "right"}
          class={"diff-line diff-line-extend" + !currentExtend.value ? " diff-line-extend-empty" : ""}
          style={{
            backgroundColor: !currentExtend.value ? `var(${emptyBGName})` : undefined,
          }}
        >
          <td class="diff-line-extend-content align-top p-0" colspan={2}>
            <div class="diff-line-extend-wrapper sticky left-0" style={{ width: width.value + "px" }}>
              {width.value > 0 &&
                currentExtend.value &&
                slots.extend?.({
                  diffFile: props.diffFile,
                  side: props.side,
                  lineNumber: currentLineNumber.value,
                  data: currentExtend.value.data,
                  onUpdate: props.diffFile.notifyAll,
                })}
            </div>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffSplitExtendLine", props: ["index", "diffFile", "lineNumber", "side"] }
);
