// packages/solid/src/components/DiffUnifiedWidgetLine.tsx
import { SplitSide, type DiffFile } from "@git-diff-view/core";
import { createMemo, Show } from "solid-js";

import { useDomWidth, useEnableWrap, useRenderWidget } from "../hooks";

import { useDiffWidgetContext } from "./DiffWidgetContext";

export const DiffUnifiedWidgetLine = (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
  const renderWidget = useRenderWidget();

  const enableWrap = useEnableWrap();

  const [widget, setWidget] = useDiffWidgetContext() || [];

  const unifiedItem = createMemo(() => props.diffFile.getUnifiedLine(props.index));

  const oldWidget = createMemo(
    () =>
      unifiedItem()?.oldLineNumber &&
      widget?.()?.side === SplitSide.old &&
      widget?.()?.lineNumber === unifiedItem()?.oldLineNumber
  );

  const newWidget = createMemo(
    () =>
      unifiedItem()?.newLineNumber &&
      widget?.()?.side === SplitSide.new &&
      widget?.()?.lineNumber === unifiedItem()?.newLineNumber
  );

  const currentIsHidden = createMemo(() => unifiedItem()?.isHidden);

  const currentIsShow = createMemo(() => !!(oldWidget() || newWidget()) && !currentIsHidden() && !!renderWidget());

  const onCloseWidget = () => setWidget?.({});

  const lineSelector = createMemo(() => `.unified-diff-table-wrapper`);

  const width = useDomWidth({
    selector: lineSelector,
    enable: () => currentIsShow(),
  });

  return (
    <Show when={currentIsShow()}>
      <tr data-line={`${props.lineNumber}-widget`} data-state="widget" class="diff-line diff-line-widget">
        <td class="diff-line-widget-content p-0" colspan={2}>
          <div class="diff-line-widget-wrapper sticky left-0 z-[1]" style={{ width: width() + "px" }}>
            {(enableWrap() ? true : width() > 0) &&
              oldWidget() &&
              renderWidget()?.({
                diffFile: props.diffFile,
                side: SplitSide.old,
                lineNumber: unifiedItem()?.oldLineNumber || 0,
                onClose: onCloseWidget,
              })}
            {(enableWrap() ? true : width() > 0) &&
              newWidget() &&
              renderWidget()?.({
                diffFile: props.diffFile,
                side: SplitSide.new,
                lineNumber: unifiedItem().newLineNumber || 0,
                onClose: onCloseWidget,
              })}
          </div>
        </td>
      </tr>
    </Show>
  );
};

// packages/vue/src/components/DiffUnifiedWidgetLine.tsx
import { computed, defineComponent, ref } from "vue";

import { SplitSide } from "..";
import { useEnableWrap, useSetWidget, useSlots, useWidget } from "../context";
import { useDomWidth } from "../hooks/useDomWidth";

import type { DiffFile } from "@git-diff-view/core";

export const DiffUnifiedWidgetLine = defineComponent(
  (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
    const slots = useSlots();

    const widget = useWidget();

    const setWidget = useSetWidget();

    const enableWrap = useEnableWrap();

    const unifiedItem = computed(() => props.diffFile.getUnifiedLine(props.index));

    const oldWidget = computed(
      () =>
        unifiedItem.value?.oldLineNumber &&
        widget?.value.side === SplitSide.old &&
        widget?.value.lineNumber === unifiedItem.value.oldLineNumber
    );

    const newWidget = computed(
      () =>
        unifiedItem.value?.newLineNumber &&
        widget?.value.side === SplitSide.new &&
        widget?.value.lineNumber === unifiedItem.value.newLineNumber
    );

    const currentIsHidden = computed(() => unifiedItem.value.isHidden);

    const currentIsShow = computed(
      () => !!(oldWidget.value || newWidget.value) && !currentIsHidden.value && !!slots?.widget
    );

    const onCloseWidget = () => setWidget?.({});

    const width = useDomWidth({
      selector: ref(".unified-diff-table-wrapper"),
      enable: currentIsShow,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr data-line={`${props.lineNumber}-widget`} data-state="widget" class="diff-line diff-line-widget">
          <td class="diff-line-widget-content p-0" colspan={2}>
            <div class="diff-line-widget-wrapper sticky left-0 z-[1]" style={{ width: width.value + "px" }}>
              {(enableWrap?.value ? true : width.value > 0) &&
                oldWidget.value &&
                slots?.widget?.({
                  diffFile: props.diffFile,
                  side: SplitSide.old,
                  lineNumber: unifiedItem.value.oldLineNumber ?? -1,
                  onClose: onCloseWidget,
                })}
              {(enableWrap?.value ? true : width.value > 0) &&
                newWidget.value &&
                slots?.widget?.({
                  diffFile: props.diffFile,
                  side: SplitSide.new,
                  lineNumber: unifiedItem.value.newLineNumber ?? -1,
                  onClose: onCloseWidget,
                })}
            </div>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffUnifiedWidgetLine", props: ["diffFile", "index", "lineNumber"] }
);
