// packages/solid/src/components/DiffView.tsx
/* eslint-disable @typescript-eslint/no-unnecessary-type-constraint */
import { _cacheMap, DiffFile, SplitSide } from "@git-diff-view/core";
import { diffFontSizeName, DiffModeEnum } from "@git-diff-view/utils";
import { type JSXElement, type JSX, createSignal, createEffect, createMemo, onCleanup, Show } from "solid-js";

import { DiffSplitView } from "./DiffSplitView";
import { DiffUnifiedView } from "./DiffUnifiedView";
import { DiffViewContext } from "./DiffViewContext";
import { DiffWidgetContext } from "./DiffWidgetContext";
import { createDiffConfigStore } from "./tools";

import type { DiffHighlighter, DiffHighlighterLang } from "@git-diff-view/core";

_cacheMap.name = "@git-diff-view/solid";

export { SplitSide, DiffModeEnum };

export type DiffViewProps<T> = {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | string | null; content?: string | null };
    hunks: string[];
  };
  extendData?: { oldFile?: Record<string, { data: T } | undefined>; newFile?: Record<string, { data: T } | undefined> };
  initialWidgetState?: { side: SplitSide; lineNumber: number };
  diffFile?: DiffFile;
  class?: string;
  style?: JSX.CSSProperties;
  registerHighlighter?: Omit<DiffHighlighter, "getHighlighterEngine">;
  diffViewMode?: DiffModeEnum;
  diffViewWrap?: boolean;
  diffViewTheme?: "light" | "dark";
  diffViewFontSize?: number;
  diffViewHighlight?: boolean;
  diffViewAddWidget?: boolean;
  renderWidgetLine?: ({
    diffFile,
    side,
    lineNumber,
    onClose,
  }: {
    lineNumber: number;
    side: SplitSide;
    diffFile: DiffFile;
    onClose: () => void;
  }) => JSXElement;
  renderExtendLine?: ({
    diffFile,
    side,
    data,
    lineNumber,
    onUpdate,
  }: {
    lineNumber: number;
    side: SplitSide;
    data: T;
    diffFile: DiffFile;
    onUpdate: () => void;
  }) => JSXElement;
  onAddWidgetClick?: (lineNumber: number, side: SplitSide) => void;
};

type DiffViewProps_1<T> = Omit<DiffViewProps<T>, "data"> & {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: DiffHighlighterLang | null; content?: string | null };
    hunks: string[];
  };
};

type DiffViewProps_2<T> = Omit<DiffViewProps<T>, "data"> & {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    hunks: string[];
  };
};

const InternalDiffView = <T extends unknown>(props: DiffViewProps<T>) => {
  const getInstance = () => {
    let diffFile: DiffFile | null = null;
    if (props.diffFile) {
      diffFile = DiffFile.createInstance({});
      diffFile._mergeFullBundle(props.diffFile._getFullBundle());
    } else if (props.data) {
      diffFile = new DiffFile(
        props.data.oldFile?.fileName || "",
        props.data.oldFile?.content || "",
        props.data.newFile?.fileName || "",
        props.data.newFile?.content || "",
        props.data.hunks || [],
        props.data.oldFile?.fileLang || "",
        props.data.newFile?.fileLang || ""
      );
    }

    onCleanup(() => diffFile?.clear?.());

    return diffFile;
  };

  const [wrapperRef, setWrapRef] = createSignal<HTMLDivElement | null>(null);

  const diffFile = createMemo(getInstance);

  const [isMounted, setIsMounted] = createSignal(false);

  createEffect(() => {
    setIsMounted(true);
  });

  const [widgetState, setWidgetState] = createSignal<{ side?: SplitSide; lineNumber?: number }>({
    side: props.initialWidgetState?.side,
    lineNumber: props.initialWidgetState?.lineNumber,
  });

  const reactiveHook = createDiffConfigStore(props, diffFile()?.getId() || "");

  createEffect(() => {
    const {
      setId,
      setEnableAddWidget,
      setEnableHighlight,
      setEnableWrap,
      setExtendData,
      setFontSize,
      setIsIsMounted,
      setMode,
      setOnAddWidgetClick,
      setRenderExtendLine,
      setRenderWidgetLine,
    } = reactiveHook.getReadonlyState();
    const currentDiffFile = diffFile();

    setId(currentDiffFile?.getId() || "");

    setEnableAddWidget(!!props.diffViewAddWidget);

    setEnableHighlight(!!props.diffViewHighlight);

    setEnableWrap(!!props.diffViewWrap);

    setFontSize(props.diffViewFontSize || 14);

    setIsIsMounted(isMounted());

    setMode(props.diffViewMode || DiffModeEnum.Split);

    setOnAddWidgetClick({ current: props.onAddWidgetClick });

    setRenderExtendLine(props.renderExtendLine);

    setRenderWidgetLine(props.renderWidgetLine);

    setExtendData(props.extendData);
  });

  createEffect(() => {
    if (props.initialWidgetState) {
      setWidgetState({
        side: props.initialWidgetState.side,
        lineNumber: props.initialWidgetState.lineNumber,
      });
    }
  });

  const initSubscribe = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && props.diffFile && currentDiffFile) {
      props.diffFile._addClonedInstance(currentDiffFile);
      onCleanup(() => props.diffFile?._delClonedInstance(currentDiffFile));
    }
  };

  const initDiff = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && currentDiffFile) {
      currentDiffFile.initTheme(props.diffViewTheme);
      currentDiffFile.initRaw();
      currentDiffFile.buildSplitDiffLines();
      currentDiffFile.buildUnifiedDiffLines();
    }
  };

  const initSyntax = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    if (mounted && currentDiffFile && props.diffViewHighlight) {
      currentDiffFile.initSyntax({ registerHighlighter: props.registerHighlighter });
      currentDiffFile.notifyAll();
    }
  };

  const initAttribute = () => {
    const mounted = isMounted();
    const currentDiffFile = diffFile();
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    props.diffViewTheme;
    if (mounted && currentDiffFile && wrapperRef()) {
      const init = () => {
        wrapperRef()?.setAttribute("data-theme", currentDiffFile._getTheme() || "light");
        wrapperRef()?.setAttribute("data-highlighter", currentDiffFile._getHighlighterName());
      };

      init();

      const cb = currentDiffFile.subscribe(init);

      onCleanup(() => cb());
    }
  };

  createEffect(initSubscribe);

  createEffect(initDiff);

  createEffect(initSyntax);

  createEffect(initAttribute);

  onCleanup(() => reactiveHook.clear());

  return (
    <Show when={diffFile()}>
      <div
        class="diff-tailwindcss-wrapper"
        data-component="git-diff-view"
        data-theme={diffFile()?._getTheme?.() || "light"}
        data-version={__VERSION__}
        data-highlighter={diffFile()?._getHighlighterName?.()}
        ref={setWrapRef}
      >
        <DiffViewContext.Provider value={reactiveHook}>
          <DiffWidgetContext.Provider value={[widgetState, setWidgetState]}>
            <div class="diff-style-root" style={{ [diffFontSizeName]: (props.diffViewFontSize || 14) + "px" }}>
              <div
                id={isMounted() ? `diff-root${diffFile()?.getId()}` : undefined}
                class={"diff-view-wrapper" + (props.class ? ` ${props.class}` : "")}
                style={props.style}
              >
                {!props.diffViewMode || props.diffViewMode & DiffModeEnum.Split ? (
                  <DiffSplitView diffFile={diffFile() as DiffFile} />
                ) : (
                  <DiffUnifiedView diffFile={diffFile() as DiffFile} />
                )}
              </div>
            </div>
          </DiffWidgetContext.Provider>
        </DiffViewContext.Provider>
      </div>
    </Show>
  );
};

function SolidDiffView<T>(props: DiffViewProps_1<T>): JSXElement;
function SolidDiffView<T>(props: DiffViewProps_2<T>): JSXElement;
function SolidDiffView<T>(props: DiffViewProps<T>): JSXElement {
  return <InternalDiffView {...props} />;
}

export const DiffView = SolidDiffView;

// packages/vue/src/components/DiffView.tsx
import { DiffFile, _cacheMap, SplitSide } from "@git-diff-view/core";
import { diffFontSizeName, DiffModeEnum } from "@git-diff-view/utils";
import { defineComponent, provide, ref, watch, watchEffect, computed, onUnmounted } from "vue";

import {
  idSymbol,
  modeSymbol,
  fontSizeSymbol,
  enableWrapSymbol,
  enableHighlightSymbol,
  enableAddWidgetSymbol,
  extendDataSymbol,
  slotsSymbol,
  onAddWidgetClickSymbol,
  widgetStateSymbol,
  setWidgetStateSymbol,
  mountedSymbol,
  domSymbol,
} from "../context";
import { useIsMounted } from "../hooks/useIsMounted";
import { useProvide } from "../hooks/useProvide";

import { DiffSplitView } from "./DiffSplitView";
import { DiffUnifiedView } from "./DiffUnifiedView";

import type { DiffHighlighter } from "@git-diff-view/core";
import type { CSSProperties, SlotsType } from "vue";

_cacheMap.name = "@git-diff-view/vue";

export { SplitSide, DiffModeEnum };

export type DiffViewProps<T> = {
  data?: {
    oldFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    newFile?: { fileName?: string | null; fileLang?: string | null; content?: string | null };
    hunks: string[];
  };
  extendData?: { oldFile?: Record<string, { data: T }>; newFile?: Record<string, { data: T }> };
  initialWidgetState?: { side: SplitSide; lineNumber: number };
  diffFile?: DiffFile;
  class?: string;
  style?: CSSProperties;
  registerHighlighter?: Omit<DiffHighlighter, "getHighlighterEngine">;
  diffViewMode?: DiffModeEnum;
  diffViewWrap?: boolean;
  diffViewTheme?: "light" | "dark";
  diffViewFontSize?: number;
  diffViewHighlight?: boolean;
  diffViewAddWidget?: boolean;
};

type typeSlots = SlotsType<{
  widget: { lineNumber: number; side: SplitSide; diffFile: DiffFile; onClose: () => void };
  extend: { lineNumber: number; side: SplitSide; data: any; diffFile: DiffFile; onUpdate: () => void };
}>;

// vue 组件打包目前无法支持范型 也不支持 slots
export const DiffView = defineComponent<
  DiffViewProps<any>,
  { onAddWidgetClick: (lineNumber: number, side: SplitSide) => void },
  "onAddWidgetClick",
  typeSlots
>(
  (props, options) => {
    const getInstance = () => {
      if (props.diffFile) {
        const diffFile = DiffFile.createInstance({});
        diffFile._mergeFullBundle(props.diffFile._getFullBundle());
        return diffFile;
      }
      if (props.data)
        return new DiffFile(
          props.data.oldFile?.fileName || "",
          props.data.oldFile?.content || "",
          props.data.newFile?.fileName || "",
          props.data.newFile?.content || "",
          props.data.hunks || [],
          props.data.oldFile?.fileLang || "",
          props.data.newFile?.fileLang || ""
        );
      return null;
    };

    const diffFile = ref<DiffFile>(getInstance());

    const id = ref(diffFile.value?.getId?.());

    const widgetState = ref<{ side?: SplitSide; lineNumber?: number }>({});

    const wrapperRef = ref<HTMLDivElement>();

    const setWidget = (v: { side?: SplitSide; lineNumber?: number }) => {
      if (typeof options.slots.widget === "function") {
        widgetState.value = v;
      }
    };

    const enableHighlight = computed(() => props.diffViewHighlight ?? true);

    const theme = computed(() => props.diffViewTheme);

    watch(
      () => props.diffFile,
      () => {
        diffFile.value?.clear?.();
        diffFile.value = getInstance();
      },
      { immediate: true }
    );

    watch(
      () => props.initialWidgetState,
      () => {
        if (props.initialWidgetState) {
          widgetState.value = {
            side: props.initialWidgetState.side,
            lineNumber: props.initialWidgetState.lineNumber,
          };
        }
      },
      { immediate: true, deep: true }
    );

    watch(
      () => props.data,
      () => {
        diffFile.value?.clear?.();
        diffFile.value = getInstance();
      },
      { immediate: true, deep: true }
    );

    watch(
      () => diffFile.value,
      () => (widgetState.value = {})
    );

    const isMounted = useIsMounted();

    const initSubscribe = (onClean: (cb: () => void) => void) => {
      if (!isMounted.value || !diffFile.value || !props.diffFile) return;
      const instance = diffFile.value as DiffFile;
      props.diffFile._addClonedInstance(instance);
      onClean(() => props.diffFile._delClonedInstance(instance));
    };

    const initDiff = () => {
      if (!isMounted.value || !diffFile.value) return;
      const instance = diffFile.value;
      instance.initTheme(theme.value);
      instance.initRaw();
      instance.buildSplitDiffLines();
      instance.buildUnifiedDiffLines();
    };

    const initSyntax = () => {
      if (!isMounted.value || !diffFile.value) return;

      const instance = diffFile.value;

      // eslint-disable-next-line @typescript-eslint/no-unused-expressions
      theme.value;

      if (enableHighlight.value) {
        const registerHighlighter = props.registerHighlighter;
        if (registerHighlighter) {
          instance.initSyntax({
            registerHighlighter: registerHighlighter,
          });
        } else {
          instance.initSyntax({});
        }
        instance.notifyAll();
      }
    };

    const initAttribute = (onClean: (cb: () => void) => void) => {
      if (!isMounted.value || !diffFile.value || !wrapperRef.value) return;

      const instance = diffFile.value;

      // eslint-disable-next-line @typescript-eslint/no-unused-expressions
      theme.value;

      const init = () => {
        wrapperRef.value?.setAttribute("data-theme", instance._getTheme() || "light");
        wrapperRef.value?.setAttribute("data-highlighter", instance._getHighlighterName());
      };

      init();

      const cb = instance.subscribe(init);

      onClean(() => cb());
    };

    const initId = (onClean: (cb: () => void) => void) => {
      if (!diffFile.value) return;
      const instance = diffFile.value;
      id.value = instance.getId();
      onClean(() => instance.clearId());
    };

    watchEffect((onClean) => initSubscribe(onClean));

    watchEffect(() => initDiff());

    watchEffect(() => initSyntax());

    watchEffect((onClean) => initId(onClean));

    watchEffect((onClean) => initAttribute(onClean));

    provide(idSymbol, id);

    provide(domSymbol, wrapperRef);

    provide(mountedSymbol, isMounted);

    provide(slotsSymbol, options.slots);

    provide(onAddWidgetClickSymbol, options.emit);

    provide(widgetStateSymbol, widgetState);

    provide(setWidgetStateSymbol, setWidget);

    useProvide(props, "diffViewMode", modeSymbol, { defaultValue: DiffModeEnum.SplitGitHub });

    useProvide(props, "diffViewFontSize", fontSizeSymbol, { defaultValue: 14 });

    useProvide(props, "diffViewWrap", enableWrapSymbol);

    useProvide(props, "diffViewHighlight", enableHighlightSymbol);

    useProvide(props, "diffViewAddWidget", enableAddWidgetSymbol);

    useProvide(props, "extendData", extendDataSymbol, { deepWatch: true });

    onUnmounted(() => diffFile.value?.clear?.());

    options.expose({ getDiffFileInstance: () => diffFile.value });

    return () => {
      if (!diffFile.value) return null;

      return (
        <div
          class="diff-tailwindcss-wrapper"
          data-component="git-diff-view"
          data-theme={diffFile.value._getTheme() || "light"}
          data-version={__VERSION__}
          data-highlighter={diffFile.value._getHighlighterName()}
          ref={wrapperRef}
        >
          <div class="diff-style-root" style={{ [diffFontSizeName]: (props.diffViewFontSize || 14) + "px" }}>
            <div
              // fix ssr mismatch error
              id={isMounted.value ? `diff-root${id.value}` : undefined}
              class={"diff-view-wrapper" + (props.class ? ` ${props.class}` : "")}
              style={props.style}
            >
              {!props.diffViewMode || props.diffViewMode & DiffModeEnum.Split ? (
                <DiffSplitView key={DiffModeEnum.Split} diffFile={diffFile.value as DiffFile} />
              ) : (
                <DiffUnifiedView key={DiffModeEnum.Unified} diffFile={diffFile.value as DiffFile} />
              )}
            </div>
          </div>
        </div>
      );
    };
  },
  {
    name: "DiffView",
    props: [
      "data",
      "class",
      "diffFile",
      "diffViewAddWidget",
      "diffViewFontSize",
      "diffViewHighlight",
      "diffViewMode",
      "diffViewWrap",
      "diffViewTheme",
      "extendData",
      "registerHighlighter",
      "initialWidgetState",
      "style",
    ],
    // expose: ["getDiffView"],
    slots: Object as typeSlots,
  }
);

export const version = __VERSION__;
