// packages/cli/src/components/DiffSplitExtendLine.tsx
import { Box, Text } from "ink";
import * as React from "react";

import { SplitSide } from "..";

import { diffEmptyContent } from "./color";
import { useDiffViewContext } from "./DiffViewContext";

import type { DiffFile } from "@git-diff-view/core";

const InternalDiffSplitExtendLine = ({
  index,
  columns,
  theme,
  diffFile,
  lineNumber,
  oldLineExtend,
  newLineExtend,
}: {
  index: number;
  columns: number;
  theme: "light" | "dark";
  diffFile: DiffFile;
  lineNumber: number;
  oldLineExtend: { data: any };
  newLineExtend: { data: any };
}) => {
  const { useDiffContext } = useDiffViewContext();

  const oldLine = diffFile.getSplitLeftLine(index);

  const newLine = diffFile.getSplitRightLine(index);

  // 需要显示的时候才进行方法订阅，可以大幅度提高性能
  const renderExtendLine = useDiffContext.useShallowStableSelector((s) => s.renderExtendLine);

  if (!renderExtendLine) return null;

  const oldExtendRendered =
    oldLineExtend?.data &&
    renderExtendLine?.({
      diffFile,
      side: SplitSide.old,
      lineNumber: oldLine.lineNumber ?? -1,
      data: oldLineExtend.data,
      onUpdate: diffFile.notifyAll,
    });

  const newExtendRendered =
    newLineExtend?.data &&
    renderExtendLine?.({
      diffFile,
      side: SplitSide.new,
      lineNumber: newLine.lineNumber ?? -1,
      data: newLineExtend.data,
      onUpdate: diffFile.notifyAll,
    });

  const bgColor = theme === "light" ? diffEmptyContent.light : diffEmptyContent.dark;

  return (
    <Box data-line={`${lineNumber}-extend`} data-state="extend">
      <Box width={columns / 2} flexShrink={0} flexGrow={0} backgroundColor={oldExtendRendered ? undefined : bgColor}>
        {React.isValidElement(oldExtendRendered) ? oldExtendRendered : <Text>{oldExtendRendered}</Text>}
      </Box>
      <Box width={columns / 2} flexShrink={0} flexGrow={0} backgroundColor={newExtendRendered ? undefined : bgColor}>
        {React.isValidElement(newExtendRendered) ? newExtendRendered : <Text>{newExtendRendered}</Text>}
      </Box>
    </Box>
  );
};

export const DiffSplitExtendLine = ({
  index,
  columns,
  theme,
  diffFile,
  lineNumber,
}: {
  index: number;
  columns: number;
  theme: "light" | "dark";
  diffFile: DiffFile;
  lineNumber: number;
}) => {
  const { useDiffContext } = useDiffViewContext();

  const oldLine = diffFile.getSplitLeftLine(index);

  const newLine = diffFile.getSplitRightLine(index);

  const { oldLineExtend, newLineExtend } = useDiffContext(
    React.useCallback(
      (s) => ({
        oldLineExtend: s.extendData?.oldFile?.[oldLine?.lineNumber ?? -1],
        newLineExtend: s.extendData?.newFile?.[newLine?.lineNumber ?? -1],
      }),
      [oldLine?.lineNumber, newLine?.lineNumber]
    )
  );

  const hasExtend = oldLineExtend?.data || newLineExtend?.data;

  // if the expand action not enabled, the `isHidden` property will never change
  const enableExpand = diffFile.getExpandEnabled();

  const currentIsShow = hasExtend && ((!oldLine?.isHidden && !newLine?.isHidden) || !enableExpand);

  if (!currentIsShow) return null;

  return (
    <InternalDiffSplitExtendLine
      index={index}
      theme={theme}
      columns={columns}
      diffFile={diffFile}
      lineNumber={lineNumber}
      oldLineExtend={oldLineExtend}
      newLineExtend={newLineExtend}
    />
  );
};

// packages/vue/src/components/DiffSplitExtendLine.tsx
import { computed, defineComponent, ref } from "vue";

import { useExtendData, useSlots } from "../context";
import { useDomWidth } from "../hooks/useDomWidth";
import { useSubscribeDiffFile } from "../hooks/useSubscribeDiffFile";
import { useSyncHeight } from "../hooks/useSyncHeight";

import { emptyBGName } from "./color";
import { SplitSide } from "./DiffView";

import type { DiffFile } from "@git-diff-view/core";

export const DiffSplitExtendLine = defineComponent(
  (props: { index: number; side: SplitSide; diffFile: DiffFile; lineNumber: number }) => {
    const extendData = useExtendData();

    const slots = useSlots();

    const side = computed(() => (props.side === SplitSide.old ? "left" : "right"));

    const lineSelector = computed(() => `tr[data-line="${props.lineNumber}-extend"]`);

    const wrapperSelector = computed(() =>
      props.side === SplitSide.old ? ".old-diff-table-wrapper" : ".new-diff-table-wrapper"
    );

    const oldItem = ref(props.diffFile.getSplitLeftLine(props.index));

    const newItem = ref(props.diffFile.getSplitRightLine(props.index));

    const enableExpand = ref(props.diffFile.getExpandEnabled());

    const currentItem = computed(() => (props.side === SplitSide.old ? oldItem.value : newItem.value));

    const oldExtend = ref(extendData.value?.oldFile?.[oldItem.value?.lineNumber]);

    const newExtend = ref(extendData.value?.newFile?.[newItem.value.lineNumber]);

    useSubscribeDiffFile(props, (diffFile) => {
      oldItem.value = diffFile.getSplitLeftLine(props.index);

      newItem.value = diffFile.getSplitRightLine(props.index);

      oldExtend.value = extendData.value?.oldFile?.[oldItem.value?.lineNumber];

      newExtend.value = extendData.value?.newFile?.[newItem.value.lineNumber];

      enableExpand.value = diffFile.getExpandEnabled();
    });

    const currentExtend = computed(() => (props.side === SplitSide.old ? oldExtend.value : newExtend.value));

    const currentEnable = computed(() => (props.side === SplitSide.old ? !!oldExtend.value : !!newExtend.value));

    const currentLineNumber = computed(() =>
      props.side === SplitSide.old ? oldItem.value.lineNumber : newItem.value.lineNumber
    );

    const currentIsShow = computed(() =>
      Boolean(
        (oldExtend.value || newExtend.value) && currentItem.value && (!currentItem.value.isHidden || enableExpand.value)
      )
    );

    useSyncHeight({
      selector: lineSelector,
      side: side,
      enable: currentEnable,
    });

    const width = useDomWidth({
      selector: wrapperSelector,
      enable: currentEnable,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr
          data-line={`${props.lineNumber}-extend`}
          data-state="extend"
          data-side={props.side === SplitSide.old ? "left" : "right"}
          class={"diff-line diff-line-extend" + (!currentExtend.value ? " diff-line-extend-empty" : "")}
          style={{
            backgroundColor: !currentExtend.value ? `var(${emptyBGName})` : undefined,
          }}
        >
          <td class="diff-line-extend-content align-top p-0" colspan={2}>
            <div class="diff-line-extend-wrapper sticky left-0" style={{ width: width.value + "px" }}>
              {width.value > 0 &&
                currentExtend.value &&
                slots.extend?.({
                  diffFile: props.diffFile,
                  side: props.side,
                  lineNumber: currentLineNumber.value,
                  data: currentExtend.value.data,
                  onUpdate: props.diffFile.notifyAll,
                })}
            </div>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffSplitExtendLine", props: ["index", "diffFile", "lineNumber", "side"] }
);
