// packages/svelte/src/lib/components/DiffUnifiedWidgetLine.svelte
<script lang="ts">
	import { getRenderWidget } from '$lib/context/renderWidget.js';
	import { getWidget } from '$lib/context/widget.js';
	import { useDomWidth } from '$lib/hooks/useDomWidth.svelte.js';
	import { SplitSide, type DiffFile } from '@git-diff-view/core';

	interface Props {
		index: number;
		diffFile: DiffFile;
		lineNumber: number;
	}

	let props: Props = $props();

	const widget = $derived.by(getWidget());

	const renderWidget = $derived.by(getRenderWidget());

	const unifiedItem = $derived.by(() => props.diffFile.getUnifiedLine(props.index));

	const oldWidget = $derived.by(
		() =>
			unifiedItem?.oldLineNumber &&
			widget.side === SplitSide.old &&
			widget.lineNumber === unifiedItem.oldLineNumber
	);

	const newWidget = $derived.by(
		() =>
			unifiedItem?.newLineNumber &&
			widget.side === SplitSide.new &&
			widget.lineNumber === unifiedItem.newLineNumber
	);

	const currentIsHidden = $derived.by(() => unifiedItem.isHidden);

	const currentIsShow = $derived.by(() =>
		Boolean((oldWidget || newWidget) && !currentIsHidden && renderWidget)
	);

	const onCloseWidget = () => {
		widget.side = undefined;
		widget.lineNumber = undefined;
	};

	const width = $derived.by(
		useDomWidth({
			selector: () => `.unified-diff-table-wrapper`,
			enable: () => currentIsShow
		})
	);
</script>

{#if currentIsShow}
	<tr
		data-line={`${props.lineNumber}-widget`}
		data-state="widget"
		class="diff-line diff-line-widget"
	>
		<td class="diff-line-widget-content p-0" colspan={2}>
			<div class="diff-line-widget-wrapper sticky left-0 z-[1]" style={`width: ${width}px`}>
				{#if width > 0 && oldWidget}
					{@render renderWidget({
						diffFile: props.diffFile,
						side: SplitSide.old,
						lineNumber: unifiedItem.oldLineNumber || 0,
						onClose: onCloseWidget
					})}
				{/if}
				{#if width > 0 && newWidget}
					{@render renderWidget?.({
						diffFile: props.diffFile,
						side: SplitSide.new,
						lineNumber: unifiedItem.newLineNumber || 0,
						onClose: onCloseWidget
					})}
				{/if}
			</div>
		</td>
	</tr>
{/if}

// packages/vue/src/components/DiffUnifiedWidgetLine.tsx
import { computed, defineComponent, ref } from "vue";

import { SplitSide } from "..";
import { useSetWidget, useSlots, useWidget } from "../context";
import { useDomWidth } from "../hooks/useDomWidth";

import type { DiffFile } from "@git-diff-view/core";

export const DiffUnifiedWidgetLine = defineComponent(
  (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
    const slots = useSlots();

    const widget = useWidget();

    const setWidget = useSetWidget();

    const unifiedItem = computed(() => props.diffFile.getUnifiedLine(props.index));

    const oldWidget = computed(
      () =>
        unifiedItem.value?.oldLineNumber &&
        widget.value.side === SplitSide.old &&
        widget.value.lineNumber === unifiedItem.value.oldLineNumber
    );

    const newWidget = computed(
      () =>
        unifiedItem.value?.newLineNumber &&
        widget.value.side === SplitSide.new &&
        widget.value.lineNumber === unifiedItem.value.newLineNumber
    );

    const currentIsHidden = computed(() => unifiedItem.value.isHidden);

    const currentIsShow = computed(
      () => (oldWidget.value || newWidget.value) && !currentIsHidden.value && !!slots.widget
    );

    const onCloseWidget = () => setWidget({});

    const width = useDomWidth({
      selector: ref(".unified-diff-table-wrapper"),
      enable: currentIsShow,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr data-line={`${props.lineNumber}-widget`} data-state="widget" class="diff-line diff-line-widget">
          <td class="diff-line-widget-content p-0" colspan={2}>
            <div class="diff-line-widget-wrapper sticky left-0 z-[1]" style={{ width: width.value + "px" }}>
              {width.value > 0 &&
                oldWidget.value &&
                slots.widget?.({
                  diffFile: props.diffFile,
                  side: SplitSide.old,
                  lineNumber: unifiedItem.value.oldLineNumber,
                  onClose: onCloseWidget,
                })}
              {width.value > 0 &&
                newWidget.value &&
                slots.widget?.({
                  diffFile: props.diffFile,
                  side: SplitSide.new,
                  lineNumber: unifiedItem.value.newLineNumber,
                  onClose: onCloseWidget,
                })}
            </div>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffUnifiedWidgetLine", props: ["diffFile", "index", "lineNumber"] }
);
