// packages/svelte/src/lib/components/DiffUnifiedExtendLine.svelte
<script lang="ts">
	import { getExtend } from '$lib/context/extend.js';
	import { getRenderExtend } from '$lib/context/renderExtend.js';
	import { useDomWidth } from '$lib/hooks/useDomWidth.svelte.js';
	import { SplitSide, type DiffFile } from '@git-diff-view/core';

	interface Props {
		index: number;
		diffFile: DiffFile;
		lineNumber: number;
	}

	let props: Props = $props();

	const extendData = $derived.by(getExtend());

	const renderExtend = $derived.by(getRenderExtend());

	const unifiedItem = $derived.by(() => props.diffFile.getUnifiedLine(props.index));

	const oldExtend = $derived.by(() => extendData?.oldFile?.[unifiedItem?.oldLineNumber || -1]);

	const newExtend = $derived.by(() => extendData?.newFile?.[unifiedItem?.newLineNumber || -1]);

	const currentIsHidden = $derived.by(() => unifiedItem.isHidden);

	const currentIsShow = $derived.by(() =>
		Boolean((oldExtend || newExtend) && currentIsHidden && renderExtend)
	);

	const width = $derived.by(
		useDomWidth({
			selector: () => '.unified-diff-table-wrapper',
			enable: () => currentIsShow
		})
	);
</script>

{#if currentIsShow}
	<tr
		data-line={`${props.lineNumber}-extend`}
		data-state="extend"
		class="diff-line diff-line-extend"
	>
		<td class="diff-line-extend-content p-0 align-top" colspan={2}>
			<div class="diff-line-extend-wrapper sticky left-0 z-[1]" style={`width: ${width}px `}>
				{#if width && oldExtend && !!renderExtend}
					{@render renderExtend({
						diffFile: props.diffFile,
						side: SplitSide.old,
						data: oldExtend?.data,
						lineNumber: unifiedItem?.oldLineNumber || 0,
						onUpdate: () => props.diffFile.notifyAll()
					})}
				{/if}
				{#if width && newExtend && !!renderExtend}
					{@render renderExtend({
						diffFile: props.diffFile,
						side: SplitSide.new,
						data: newExtend?.data,
						lineNumber: unifiedItem?.newLineNumber || 0,
						onUpdate: () => props.diffFile.notifyAll()
					})}
				{/if}
			</div>
		</td>
	</tr>
{/if}

// packages/vue/src/components/DiffUnifiedExtendLine.tsx
import { computed, defineComponent, ref } from "vue";

import { SplitSide } from "..";
import { useExtendData, useSlots } from "../context";
import { useDomWidth } from "../hooks/useDomWidth";

import type { DiffFile } from "@git-diff-view/core";

export const DiffUnifiedExtendLine = defineComponent(
  (props: { index: number; diffFile: DiffFile; lineNumber: number }) => {
    const extendData = useExtendData();

    const slots = useSlots();

    const unifiedItem = computed(() => props.diffFile.getUnifiedLine(props.index));

    const oldExtend = computed(() => extendData.value?.oldFile?.[unifiedItem.value.oldLineNumber]);

    const newExtend = computed(() => extendData.value?.newFile?.[unifiedItem.value.newLineNumber]);

    const currentIsHidden = computed(() => unifiedItem.value.isHidden);

    const currentIsShow = computed(() =>
      Boolean((oldExtend.value || newExtend.value) && !currentIsHidden.value && slots.extend)
    );

    const width = useDomWidth({
      selector: ref(".unified-diff-table-wrapper"),
      enable: currentIsShow,
    });

    return () => {
      if (!currentIsShow.value) return null;

      return (
        <tr data-line={`${props.lineNumber}-extend`} data-state="extend" class="diff-line diff-line-extend">
          <td class="diff-line-extend-content p-0 align-top" colspan={2}>
            <div class="diff-line-extend-wrapper sticky left-0 z-[1]" style={{ width: width.value + "px" }}>
              {width.value > 0 &&
                oldExtend.value &&
                slots.extend({
                  diffFile: props.diffFile,
                  side: SplitSide.old,
                  lineNumber: unifiedItem.value.oldLineNumber,
                  data: oldExtend.value.data,
                  onUpdate: props.diffFile.notifyAll,
                })}
              {width.value > 0 &&
                newExtend.value &&
                slots.extend({
                  diffFile: props.diffFile,
                  side: SplitSide.new,
                  lineNumber: unifiedItem.value.newLineNumber,
                  data: newExtend.value.data,
                  onUpdate: props.diffFile.notifyAll,
                })}
            </div>
          </td>
        </tr>
      );
    };
  },
  { name: "DiffUnifiedExtendLine", props: ["diffFile", "index", "lineNumber"] }
);
